### ISSUE TITLE
Add Acrobat/Reader DC Classic track 2017 catalogs

### ISSUE THREAD

**Issue by t3easy** [DCourtel/Wsus_Package_Publisher#10]
The catalogs are missing.
https://www.adobe.com/devnet-docs/acrobatetk/tools/DesktopDeployment/sccm.html#available-catalogs

I would add a PR but couldn't find the other xmls in this repo.

**Comment by DCourtel** [comment]
Hi t3easy, thank you for the report. I will add those missing catalogs. In the meantime, you can add it manually by copying the URL in the address textbox and clicking Add this catalog

![2019-07-03_171335](https://user-images.githubusercontent.com/13787283/60603409-fc5b6400-9db5-11e9-812e-cb5c535862c0.png)

**Comment by t3easy** [comment]
Thx, I've seen how I can add them manually, just thought I could support you by sending a PR.
