### ISSUE TITLE
Missing source code?

### ISSUE THREAD

**Issue by mihailim** [DCourtel/Wsus_Package_Publisher#11]
Hi!

First of all, thank you for this very useful application!

However, the Github repo seems to be missing the actual source code for WSUSPP (noticed this while trying to debug an issue when running against a Server 2016 Core WSUS machine.) When comparing to the archived dump from Codeplex, the `code\Wsus Package Publisher\Wsus Package Publisher` directory here seems to only contain a skeleton.

The source for InstallPendingUpdates, ProductKiller, ShowPendingUpdates, CustomUpdateElements, and CustomUpdateElementViewer seem to also not have been ported over.

Is the actual code located somewhere else I couldn't find?

Thanks!

**Comment by StyleTec** [comment]
According to MIT license the source code can either be published or not. So this is officially partial closed source :)

He might also remove or migrate the partially published source code, as - from my understanding - mixing open and closed source in the same project is not possible according to MIT license.

**Comment by StyleTec** [comment]
@DCourtel can you please bring some light in the dark for us?

I'd also like to know if contribution is something that might be possible in the future. I've also wrote a publishing tool some years ago, but abandoned it because of WPP. Would love to contribute my experience into this project.

**Comment by StyleTec** [comment]
@DCourtel just wrote you an email in response to your latest issue responses.
