### ISSUE TITLE
Check for updates isn´t working

### ISSUE THREAD

**Issue by Scifire** [DCourtel/Wsus_Package_Publisher#15]
Hello,

the check for updates button in the WPP isn´t working. I tried it on version 1.3.1702.27. 
Not sure if it´s already fixed it the latest version.

Anyway thanks for this nice software :)

**Comment by DCourtel** [comment]
Before release v1.4.1912.9, WPP used an FTP server to get new its updates. This server has been decommissioned. Now WPP automatically checks and downloads for updates in the cloud.
