### ISSUE TITLE
Timestamp missing from digital signatures

### ISSUE THREAD

**Issue by SeanMaloney** [DCourtel/Wsus_Package_Publisher#17]
WPP does not seem to apply a timestamp while signing an update, so all updates fail to install after the certificate's signing period has ended.

This may not be an issue for people using 30-year self-signed certificates, but it is troublesome with relatively quick-to-expire certificates from a commercial CA provider.

Do we have a known workaround?

**Comment by DCourtel** [comment]
WPP is intended to be compatible with WSUS v3 and v4 with the same DLLs. Therefore, only features implemented in WSUS v3 AND v4 are supported. Timestamping is only supported by WSUS v4.
