### ISSUE TITLE
unable to push conf files

### ISSUE THREAD

**Issue by fireman05** [DCourtel/Wsus_Package_Publisher#18]
Hi, is it possible to push conf files /directory into the package ?
for example : I want to push a directory C:\Program Files (x86)\Mozilla Firefox\distribution with the firefox package because the classic Firefox MSI don't create this directory
![image](https://user-images.githubusercontent.com/58028843/69324514-e6f1b400-0c48-11ea-88fb-ffebcf0c3ced.png)

**Comment by DCourtel** [comment]
Hi, create a [Custom Update](https://github.com/DCourtel/Wsus_Package_Publisher/wiki/CustomUpdates) for that.
