### ISSUE TITLE
Adding Custom Variables to WPP through Custom Update Creator using 1.4.1912.9

### ISSUE THREAD

**Issue by ITNDF** [DCourtel/Wsus_Package_Publisher#20]
I'm looking for the option to ‘declare a variable to store data and using it later’ while creating custom updates... I'm not finding it for some reason in the new WPP custom update creator application (using 1.4.1912.9). Are there new direction(s) to declare variable(s) to store data?

Without it, I suddenly get this:

1/21/2020 12:50:12 PM	========================================================================================================================
1/21/2020 12:50:12 PM	Starting CustomUpdateEngine v2 with ActionFile : 
1/21/2020 12:50:12 PM	Can't find the ActionFile.

**Comment by DCourtel** [comment]
Hey ITNDF, can you tell me in which scenario you need a custom variable? In the previous release, it was only used for the exit code. In the latest release, the exit code is managed at the bottom of the form. 

![image](https://user-images.githubusercontent.com/13787283/73287596-c2dac200-41f9-11ea-823a-26c502ac05c7.png)

**Comment by ITNDF** [comment]
I use the custom variable in order to create custom installs using dell BIOS files. I found some directions from an old reddit post that involved using a custom update to create a xml file as one (of many) steps to create a suitable BIOS update that could suspend bitlocker as well.

Perhaps I don't need it with the newer version? Or I can just set it to 0? Not too sure.

One semi-related change was when using the .xml file I needed to use / instead of \ which isn't too bad.

**Comment by DCourtel** [comment]
Can you attach the XML file?

**Comment by ITNDF** [comment]
[c88d5269-d95c-490d-8faf-ffa2ec203754.txt](https://github.com/DCourtel/Wsus_Package_Publisher/files/4140705/c88d5269-d95c-490d-8faf-ffa2ec203754.txt)

XML attached as a txt file. I can confirm it works for me (I had to make some adjustments to out WSUS servers here for better sync and reporting to test it better)

**Comment by DCourtel** [comment]
Yes, the file seems to be fine and should works.
