### ISSUE TITLE
Release v1.4.1912.9 does not start

### ISSUE THREAD

**Issue by Alexandr-Falcon99** [DCourtel/Wsus_Package_Publisher#22]
I downloaded the latest release v1.4.1912.9. Unpacked to c: \ Temp, but when I try to run the "Wsus Package Publisher.exe" file, nothing happens. Moreover, when using "Release.v1.4.1906.3" everything starts normally.
The following information is listed in About Release.v1.4.1906.3:
Release: 1.4.1906.3
Server version: 3.2.7600.325
Console version: 3.2.7600.325

P.s. My native language is Russian, therefore translated using translate.google.com.

**Comment by DCourtel** [comment]
Hey Alexandr-Falcon99, what is the OS version of your server? Windows Server 2008R2 I guess.

**Comment by Alexandr-Falcon99** [comment]
Yes, you are right, Windows Server 2008 P2 SP1 is used.

**Comment by DCourtel** [comment]
Sorry, this server has reached his end-of-life and therefore not supported anymore by WPP. Please, upgrade your server or keep using WPP v1.4.1906.3. I’ve just updated the requirements on the wiki page.

**Comment by Alexandr-Falcon99** [comment]
Got it, thanks for the quick reply.
