### ISSUE TITLE
Could not load file or assembly 'EasyCompany.Controls, Version=1.0.1410.17, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

### ISSUE THREAD

**Issue by carlocesar** [DCourtel/Wsus_Package_Publisher#23]
Microsoft Windows Server 2012 R2 64bit
WSUS Version: 6.3.9600.18694
Installed packages:
Microsoft .NET Framework 4 Multi-Targeting Pack
Microsoft .NET Framework 4.5 Multi-Targeting Pack
Microsoft .NET Framework 4.5.1 Multi-Targeting Pack
Microsoft .NET Framework 4.5.2 Multi-Targeting Pack

Error:
...
11/02/2020 09:09:40	=================================================================================================================
11/02/2020 09:09:40	Starting. Release : 1.3.1507.29
11/02/2020 09:09:40	Upgrade Settings : False
11/02/2020 09:09:40	Windows was installed in : pt (Portuguese)
11/02/2020 09:09:40	Entering Void .ctor() : FrmSettings
11/02/2020 09:09:40	Language is : Anglais.
11/02/2020 09:09:40	Entering Wsus_Package_Publisher.WsusWrapper GetInstance()
11/02/2020 09:09:40	Entering Void .ctor() : UpdateControl
11/02/2020 09:09:40	Entering Void .ctor() : UpdateListViewer
11/02/2020 09:09:40	Entering Wsus_Package_Publisher.WsusWrapper GetInstance()
11/02/2020 09:09:41	UnhandledException. Something Went Wrong
11/02/2020 09:09:41	**** Could not load file or assembly 'EasyCompany.Controls, Version=1.0.1410.17, Culture=neutral, PublicKeyToken=null' or one of its dependencies. O sistema não pode encontrar o arquivo especificado.
11/02/2020 09:09:41	Entering Void .ctor() : FrmSendDebugInfo
11/02/2020 09:09:42	Entering Void lnkLblShowInformations_LinkClicked(System.Object, System.Windows.Forms.LinkLabelLinkClickedEventArgs)
11/02/2020 09:10:05	Entering Void lnkLblShowInformations_LinkClicked(System.Object, System.Windows.Forms.LinkLabelLinkClickedEventArgs)
...

Can anyone help me?

**Comment by DCourtel** [comment]
Hi carlocesar, are you using a Core edition of Windows Server 2012 R2? Do you see the file «EasyCompany.Controls.dll» in the installation folder? Can you try with the [latest release](https://github.com/DCourtel/Wsus_Package_Publisher/releases/tag/1.4.1912.9)

**Comment by carlocesar** [comment]
Hi! 


The problem was resolved. 


Thanks. 

----- Mensagem original -----

De: "David COURTEL" <notifications@github.com> 
Para: "DCourtel/Wsus_Package_Publisher" <Wsus_Package_Publisher@noreply.github.com> 
Cc: "Carlo Cesar Simioli Garcia" <carlo.garcia@embrapa.br>, "Author" <author@noreply.github.com> 
Enviadas: Terça-feira, 11 de fevereiro de 2020 12:44:54 
Assunto: Re: [DCourtel/Wsus_Package_Publisher] Could not load file or assembly 'EasyCompany.Controls, Version=1.0.1410.17, Culture=neutral, PublicKeyToken=null' or one of its dependencies. (#23) 


Hi carlocesar, are you using a Core edition of Windows Server 2012 R2? Do you see the file «EasyCompany.Controls.dll» in the installation folder? Can you try with the latest release 
— 
You are receiving this because you authored the thread. 
Reply to this email directly, view it on GitHub , or unsubscribe . 


-- 

Carlo César Simioli Garcia, Gerente de Rede 
Núcleo de Tecnologia da Informação (NTI) 
Embrapa Gado de Corte - www.embrapa.br/gado-de-corte 
Empresa Brasileira de Pesquisa Agropecuária (Embrapa) 
Campo Grande/MS 

carlo.garcia@embrapa.br 
Telefone: +55 (67) 3368-2055 Fax: +55 (67) 3368-2150 Celular: +55 (67) 98111-7991 
http://pandora.cnpgc.embrapa.br/staff/Carlo-Garcia 
Confira também: http://lattes.cnpq.br/7803230921636080 

www.embrapa.br | fb.com/embrapa | twitter.com/embrapa 
-- 
The best place in the world is at the feet of Jesus Christ! 
-- 
"Ainda que eu falasse as línguas dos homens e dos anjos, e não tivesse amor, seria como o metal que soa ou como o sino que tine. E ainda que tivesse o dom de profecia, e conhecesse todos os mistérios e toda a ciência, e ainda que tivesse toda a fé, de maneira tal que transportasse os montes, e não tivesse amor, nada seria. E ainda que distribuísse toda a minha fortuna para sustento dos pobres, e ainda que entregasse o meu corpo para ser queimado, e não tivesse amor, nada disso me aproveitaria" 1 Coríntios 13:1-3 
-- 
"Posso explicar software livre em três palavras: 
liberdade, igualdade e fraternidade." 
Richard Stallman 



____________________________________________________________________________
Aviso de confidencialidade

Esta mensagem da Empresa  Brasileira de Pesquisa  Agropecuaria (Embrapa),
empresa publica federal  regida pelo disposto  na Lei Federal no. 5.851,  de
7 de dezembro de 1972,  e  enviada exclusivamente  a seu destinatario e pode
conter informacoes  confidenciais, protegidas  por sigilo profissional.  Sua
utilizacao desautorizada  e ilegal e  sujeita o infrator as penas da lei. Se
voce  a recebeu indevidamente, queira, por gentileza, reenvia-la ao
emitente, esclarecendo o equivoco.

Confidentiality note

This message from Empresa  Brasileira de Pesquisa  Agropecuaria (Embrapa),
a government company  established under  Brazilian law (5.851/72), is
directed exclusively to  its addressee  and may contain confidential data, 
protected under  professional secrecy  rules. Its unauthorized  use is
illegal and  may subject the transgressor to the law's penalties. If you are
not the addressee, please send it back, elucidating the failure.
