### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by StephenJabs** [DCourtel/Wsus_Package_Publisher#25]
When importing from catalog, the dialog box states "Downloading (Total size unkown)".  Should say "unknown"

![Capture](https://user-images.githubusercontent.com/17179807/75159488-79d13d00-56d5-11ea-83f4-3b48c835ae42.png)

**Comment by DCourtel** [comment]
Thank you for reporting the typo. The update is on the way. You should get it within 24 h if you use the latest release from GitHub.
