### ISSUE TITLE
WPP Crash on path with space

### ISSUE THREAD

**Issue by Nobody4711** [DCourtel/Wsus_Package_Publisher#31]
Hi,

first thanks for this great Software!

But rigth now i got an WPP crash every time i want to check an path with spaces to test if the update is already installed.

i got this error if i check an RegSz Key like this:
![grafik](https://user-images.githubusercontent.com/65233384/81694700-ef8daf00-9461-11ea-8c18-ae5fd65275ab.png)
or if i want to check an File about Size like this:
![grafik](https://user-images.githubusercontent.com/65233384/81694896-2d8ad300-9462-11ea-94bb-29885d8f4f69.png)

Is there a way to get this working?

Kind Regards

**Comment by Nobody4711** [comment]
Sorry, i got this wrong.
The problem was not the space. But in the original Path there is an "&" included.
This one get WPP crashing at creating the package.

Is there a way to get this working with an path including "&"?
Thanks for your help.

**Comment by DCourtel** [comment]
Can you try to replace each & characters by &amp;

**Comment by DCourtel** [comment]
Can you try to replace each & characters by: `&amp;`

**Comment by Nobody4711** [comment]
Hi, **thanks a lot**, that way it is working and saving me a lot of time and work.
