### ISSUE TITLE
Timestamp on digital signatures

### ISSUE THREAD

**Issue by daskydasky** [DCourtel/Wsus_Package_Publisher#33]
Hi, 

I have noticed that when I create an update package there is no timestamp showing on the digital signatures tab on the CAB file.  Basically showing timestamp not available.  Is there any way to fix that?

**Comment by DCourtel** [comment]
Hi Daskydasky, the latest release of WPP will timestamp newly published updates. If you use a recent release of WPP, it should download the latest release and upgrade itself. Otherwise, you’ll have to manually download the latest version here.
