### ISSUE TITLE
Virus warning

### ISSUE THREAD

**Issue by dwarfmage** [DCourtel/Wsus_Package_Publisher#34]
Scanning the .7z files for 1.4.2002.4 and 1.4.1912.9 using the www.virustotal.com/gui reports findings. I know they are clean as I've decompressed them both, created new .zip files from the extracted files and scanned them with no findings.

Example:
.7z - https://www.virustotal.com/gui/file/7de8157fa59a9199ee76395b6cf8516ea43fa53a5a2f866a418d19d3143a523c/detection
.zip - https://www.virustotal.com/gui/file/c8cfbe6564a09ec28588f51496db8f72430a87326360ac8e2da7707c9216bc35/detection

**Comment by DCourtel** [comment]
It’s very common for AVs to flag WPP as a potential threat (mostly because of the customUpdateEngine file and based on reputation). You can ignore the result of BitDefenderTheta. I don’t use Zip files because of the poor efficiency of the compression algorithm.
