### ISSUE TITLE
Server version is different from console version. You won't be able to publish/revise updates

### ISSUE THREAD

**Issue by axcro7** [DCourtel/Wsus_Package_Publisher#35]
Hi,
This issue isn't caused by WPP but ist preventing me to use ist from an other machine than the WSUS Server itself.
Whe launching from s connection other than "local server" I get this warning:
`Server version is different from console version. You won't be able to publish/revise updates`
I have Server Version 6.3.9600.18838 and Console Version 6.3.9600.18894 (Server 2012 R2)
The funny thing is: it's the same issue when I lauch the WPP on the WSUS Server direktly when not using the option "Connect to local server"

So far I only found this old thread on technet: https://social.technet.microsoft.com/Forums/en-US/a1a44101-443b-46e6-b36a-b41400576ac7/wsus-server-version-and-wsus-console-mismatch?forum=winserverwsus
How did you resolve this back then? 
Or is it save to tick the "Ignore Console and Server version mismatch" option?

axcro

**Comment by DCourtel** [comment]
Yes, you can use the option to discard the mismatch.
