### ISSUE TITLE
Custom action restart

### ISSUE THREAD

**Issue by gabrielbsilva** [DCourtel/Wsus_Package_Publisher#36]
I have a question about the restart custom action. Is it possible to restart/shutdown before execute a file? I need something like the actions below.

1. Reboot
2. Execute a file

Sorry if this isn't the right place to have a question cleared up.

Thank you for your assistance regarding this matter.

**Comment by axcro7** [comment]
+1

I'm looking for the same feature. 
Also I would need to install updates when Windows shuts down (after logoff) and an other whenn it starts (bevore the user can log on)

Thank you!

**Comment by DCourtel** [comment]
This is not supported by the CustomUpdate engine.
