### ISSUE TITLE
Failed to sign package; error was 2147954407

### ISSUE THREAD

**Issue by dwarfmage** [DCourtel/Wsus_Package_Publisher#37]
With release 1.4.2008.16 I am getting the subject error message. It works fine on release v1.4.2002.4.

The error appears to be in relation to dns resolution and the only reference I could find was to a patchmypc page which refers to the timestamping. Patchmypc's resolution is having an option to not timestamp packages in their tool.

My WSUS server is on an isolated network with no internet connectivity (we import the patches manually). Aside from reverting to release v1.4.2002.4, is there a way to disable the timestamping when creating a package?

**Comment by DCourtel** [comment]
Please upgrade WPP to 1.4.2011.23 and disable Timestamping as explained in the release note.
https://github.com/DCourtel/Wsus_Package_Publisher/releases/tag/1.4.2011.23
