### ISSUE TITLE
Package signing does not use proxy server

### ISSUE THREAD

**Issue by daooze** [DCourtel/Wsus_Package_Publisher#38]
We use a proxy server to connect to the internet. This works great with updating catalogs but does not work with the new signing-feature. We need to manually set the systemwide proxy via `netsh winhttp set proxy` for signing to work, but this opens other issues, so this configuration needs to be reverted after an update has been imported/created.

I´d ask you to make the signing-feature use the proxy server which can already be configured within the WPP settings.

**Comment by DCourtel** [comment]
The signing process is handled by the WSUS itself (under the System account), not WPP. What is the release number of WPP?

**Comment by DCourtel** [comment]
Please upgrade WPP to 1.4.2011.23 and disable Timestamping as explained in the release note. 
https://github.com/DCourtel/Wsus_Package_Publisher/releases/tag/1.4.2011.23
