### ISSUE TITLE
Is it possible to deploy a EXE-Installer that needs user interaction as custom update?

### ISSUE THREAD

**Issue by response-ab** [DCourtel/Wsus_Package_Publisher#40]
I want to deploy updates for MS Dynamics using WPP. Unfortunately these updates are EXE-Installers that don't have any silent mode, hence silent install is not possible. (and they are not included in the windows update catalog anymore)
https://support.microsoft.com/en-us/help/3142345/microsoft-dynamics-365-onpremise-cumulative-updates

Is it possible to deploy these updates using WPP nonetheless?

I asked the same question at the wsus.de forum (https://www.wsus.de/cgi-bin/yabb/YaBB.pl?num=1603369894/) and a user told me that the "custom update" option in WPP might make it possible to deploy updates that need user interaction (he wasn't sure about that as he hasn't used custom updates so far).
Is this true? Can you use "custom update" to deploy installers with user interaction? If so, how?
Thanks!

**Comment by DCourtel** [comment]
You can deploy EXE files with or without CustomUpdate. But be aware that those updates are installed using the user account. If the EXE needs admin rights, the user must have admin rights to run it. UAC may prompt for credentials.

**Comment by response-ab** [comment]
Thanks for your reply! I have been successfully deploying EXE-Installers with WPP so far. But only if they had a silent install mode. Without silent mode, I always got an error und windows update got stuck. That's my problem with the MS Dynamics updates. They don't seem to have any silent install switch.
Is it even possible to deploy EXE-Installers with WPP/WSUS that don't have any silent mode?

**Comment by DCourtel** [comment]
Yes, you need to enable the option «Can request user input» in the Update Creation Wizard. The installer will run in the user context and the UI can be shown.

**Comment by response-ab** [comment]
Thank you. I tried that. The Update downloads successfully but it doesn't install. It is stuck at 0% and no installer-window pops up.

**Comment by DCourtel** [comment]
What’s the OS of the client computer?

**Comment by response-ab** [comment]
The Client is a Windows 10 Hyper-V virtual machine and the Server is a Windows Server 2019 Hyper-V virtual machine. 

In Hyper-V they share a private switch and can ping each other.

Test-deployments of MSI-Installers and of other EXE-Installers (using silent switches) went flawlessly so far.

Do I have to change any security settings to allow interactive installations for windows update?

**Comment by DCourtel** [comment]
I think Windows 10 doesn’t honor the CanRequestUserInput option anymore :-( 
You can try to see if the EXE installer is a wrapper for an MSI. Try to uncompress it with 7-zip.

**Comment by response-ab** [comment]
That's unfortunate! Because the Dynamics-Updates are not wrapped MSI-Installers. So there is no other solution?
Still, thanks a lot for your support so far!

**Comment by response-ab** [comment]
I was wrong. It's an MSP-file. I will try using that.

**Comment by response-ab** [comment]
Sorry for the long delay. The MSP-files don't work. If executed, there's a popup window saying that you ought to execute "crmupdatewrapper.exe" instead to start the update.

EDIT:
This exe seems to have a silent mode. I will try deploying an update with this exe and include all the other extracted files (including the MSP-file) with it.

**Comment by response-ab** [comment]
Unfortunately, it doesn't work. 
Installing it on the client directly using the cmd "CrmUpdateWrapper.exe /q" works.
Deploying it to the client with WPP doesn't work. Windows Update fails with some error code. I used CrmUpdateWrapper.exe and included all the other files of the unzipped installer in the update.
