### ISSUE TITLE
Update tree is empty after restart

### ISSUE THREAD

**Issue by m8ichael** [DCourtel/Wsus_Package_Publisher#41]
The tool recently stopped showing updates after a restart. Updates can be generated normally and without error messages, these are then also displayed in the update tree on the left. If the tool is closed and restarted, no more updates are displayed. In fact, such updates are apparently still in the database, because they can still be displayed in the WSUS console.

The problem occurs in both the current and previous versions of the software.

**Comment by DCourtel** [comment]
Please check if the option «Show locally-published Updates that are also visible in Wsus Console» in enable under Tools->Settings->Updates

**Comment by m8ichael** [comment]
Ohhh..... Thank you, that solved the problem. :-)
