### ISSUE TITLE
You do not have a certificate

### ISSUE THREAD

**Issue by patanne** [DCourtel/Wsus_Package_Publisher#42]
I  have used WPP for years and years. Never a problem. We have an extensive PKI and have used one of our own certificates for years.

Today we upgraded WSUS to Windows 2019. We were getting quirky invalid certificate errors, so we unloaded and reloaded our certificate. Now we get the message, "You do not have a certificate. You will not be able to publish updates." If we let WPP generate a self-signed cert, everything is fine.

What exactly is the code looking for to be satisfied a signing certificate is available?

**Comment by DCourtel** [comment]
Are you using a special kind of certificate? Can you try to enable the option: «Ignore Code-Signing certificate validation errors» in the servers tab of the settings.

**Comment by patanne** [comment]
david. thank you for your response. i have since found documentation that states you cannot install/import the certificate WSUS uses manually. you have to use special tools. one is from microsoft. i will be testing this tomorrow. i will let you k is what happens. 


via mobile
