### ISSUE TITLE
Microsoft reports a virus for the package 1.4.2011.23

### ISSUE THREAD

**Issue by aw-think** [DCourtel/Wsus_Package_Publisher#43]
Microsoft reports a virus for the package https://github.com/DCourtel/Wsus_Package_Publisher/releases/download/1.4.2011.23/Release.v1.4.2011.23.7z after the download.

This report is available on VirusTotal: https://www.virustotal.com/gui/file/3221b6aab9da275f0585aca6aa029b6833b92bdeddc0013d4949a4f7a73740ef/detection

This will probably be wrong, but the message is still there.

**Comment by DCourtel** [comment]
Yeah, I know. It’s not unusual for a new release of WPP to be flag as malicious. Those detections are based on ML or general behavior analyses. Besides, these files are new on the Internet.

**Comment by aw-think** [comment]
Thanks for explaining.
