### ISSUE TITLE
Scripting with WPP?

### ISSUE THREAD

**Issue by citaro104** [DCourtel/Wsus_Package_Publisher#44]
I want to fully automate a Windows Server Configuration including the installation of Active Directory, DNS, DHCP, WDS, MDT, WSUS and WPP. By now I have created a powershell script which installs AD, DNS, DHCP, WDS, MDT and WSUS. It also configures them so I won't have to do anything after running that script. But is there a way to create scripts for WPP as well? While my script is running I'm also "installing" WPP and some additional Software. I have several Softwarepackages stored in a seperate folder from where I'm installing them. Also WPP is copied from this folder to the "Program Files" Directory on Drive C. And now I want to automaticly create the certificates and create the softwareinstallationpackages for publishing via windows update by a script.

**Comment by DCourtel** [comment]
No, there is no scripting possibility in WPP. Do you often install WPP?

**Comment by citaro104** [comment]
Not at the moment but I'm planning to.
