### ISSUE TITLE
Error running Wsus Package Publisher.exe

### ISSUE THREAD

**Issue by alvarocerna** [DCourtel/Wsus_Package_Publisher#45]
Dear, I have downloaded the source from the link https://codeplexarchive.blob.core.windows.net/archive/projects/WsusPackagePublisher/WsusPackagePublisher.zip but when executing it from ...... \ WsusPackagePublisher \ sourceCode \ wsuspackagepublisher \ Wsus Package Publisher \ obj \ Release the error appears:
Could not load file or assembly 'EasyCompany.Controls, Version = 1.0.1410.17, Culture = neutral, PublicKeyToken = null' or one of its dependencies. The system cannot find the file specified.

WSUS service is on Windows Server 2016 STD server, please support it.

**Comment by DCourtel** [comment]
Please, download from the [release page](https://github.com/DCourtel/Wsus_Package_Publisher/releases)
