### ISSUE TITLE
issue with remote MSI manager

### ISSUE THREAD

**Issue by fireman05** [DCourtel/Wsus_Package_Publisher#47]
unable to launch Remote MSI manager with WPP.
app crashes immediately.
Version WPP 1.4.2011.23 with remote MSI V 1.0.1912.2 , WSUS server W2012R2 updated
error code : 
Application : RemoteMsiManager.exe Version du Framework : v4.0.30319 Description : le processus a été arrêté en raison d'une exception non gérée. Informations sur l'exception : System.IO.FileNotFoundException à RemoteMsiManager.Program.Main(System.String[]) 

Anyone have un idea ?

**Comment by DCourtel** [comment]
Can you upgrade to WPP v1.4.2103.13 and let me know if that fixes the issue?

**Comment by fireman05** [comment]
Hi David, with your update , I can launch Remote MSI manager. 
this issue is fixed.
Thank you for your help and your implication
