### ISSUE TITLE
Failed to sign package; error was 2147954402

### ISSUE THREAD

**Issue by st00785** [DCourtel/Wsus_Package_Publisher#48]
Getting the following when I try to publish new packages on a Windows Server 2019 WSUS server. I have been able to publish such packages previously (I've recently upgraded to v1.4.2011.23 so it could be related?) - the package will look like it is about to publish before failing and say "Failed to sign package; error was 2147954402"

Any ideas

**Comment by st00785** [comment]
I can confirm if I roll WPP back to an older version e.g. 1.4.1904.29 then I can deploy packages fine so me thinks there is an issue with the newer version?

**Comment by DCourtel** [comment]
Hi, I can publish to WSUS 2019 with the latest version of WPP. Can you look into the publisher log (%LocalAppData%\Temp) to see if any error message appears?

**Comment by DCourtel** [comment]
Also, ensure your WSUS server can access Internet to use the timestamping option.
