### ISSUE TITLE
WPP crash at final step of distributing a package (log attached)

### ISSUE THREAD

**Issue by christophstephan** [DCourtel/Wsus_Package_Publisher#50]
[WPP-5e24a989-0f4c-46fd-9a14-efe3cf7b975e.log.gz](https://github.com/DCourtel/Wsus_Package_Publisher/files/5966035/WPP-5e24a989-0f4c-46fd-9a14-efe3cf7b975e.log.gz)
Wsus Package Publisher breaks down (terminates) at the final step (when trying to distribute the package I have just created)
WPP version 1.4.2011.23 / Windows Server 2012R2 / WSUS Version 6.3.9600.18694
Your help is highly appreciated.

**Comment by christophstephan** [comment]
I've used wrong parameters. Fixed it myself.

**Comment by xbit11111111** [comment]
> I've used wrong parameters. Fixed it myself.

Hi. Do you maybe remember which wrong parameters you used? I'm facing the same issue with "ThreadException. Something Went Wrong".
Vielen Dank
[WPP-e52eadcc-0439-491f-9347-2be7ead3d7b5.log](https://github.com/user-attachments/files/16508089/WPP-e52eadcc-0439-491f-9347-2be7ead3d7b5.log)

**Comment by christophstephan** [comment]
Sorry, this is far too long ago. I do not remember the details any more.

[Signatur / Signature]<https://www.ubert.com/>
[Vertraulichkeitserklaerung / Confidentiality Disclaimer]<https://www.ubert.com/youtube>
[Besuchen Sie unsere Website / Visit our website]<https://www.ubert.com/newsletter>
Von: xbit11111111 ***@***.***>
Gesendet: Dienstag, 6. August 2024 11:05
An: DCourtel/Wsus_Package_Publisher ***@***.***>
Cc: Stephan, Christoph ***@***.***>; State change ***@***.***>
Betreff: Re: [DCourtel/Wsus_Package_Publisher] WPP crash at final step of distributing a package (log attached) (#50)


I've used wrong parameters. Fixed it myself.

Hi. Do you maybe remember which wrong parameters you used? I'm facing the same issue with "ThreadException. Something Went Wrong".
Vielen Dank
WPP-e52eadcc-0439-491f-9347-2be7ead3d7b5.log<https://github.com/user-attachments/files/16508089/WPP-e52eadcc-0439-491f-9347-2be7ead3d7b5.log>

-
