### ISSUE TITLE
error 2149122451   creating update

### ISSUE THREAD

**Issue by ArielBaravalle** [DCourtel/Wsus_Package_Publisher#52]
Hello.
I try to create a update of different msi files ,  and receive in all times the error 
![image](https://user-images.githubusercontent.com/9282436/109928557-db9f8c00-7cc5-11eb-9c3f-ef58d6e6ec32.png)

![image](https://user-images.githubusercontent.com/9282436/109928606-e9eda800-7cc5-11eb-80b0-c4f17fbc1038.png)

thanks.

**Comment by DCourtel** [comment]
Hi, can you go to %LocalAppData%\Temp to look at WPP-GUI.log to see if any error message is reported?

**Comment by ArielBaravalle** [comment]
[WPP-f4e235ad-23f7-4d5c-b776-1a5f55303b3e.log](https://github.com/DCourtel/Wsus_Package_Publisher/files/6165211/WPP-f4e235ad-23f7-4d5c-b776-1a5f55303b3e.log)

hello,  tanks for you reply ,   I attached  the file log.

**Comment by ArielBaravalle** [comment]
[WPP-f4e235ad-23f7-4d5c-b776-1a5f55303b3e.log](https://github.com/DCourtel/Wsus_Package_Publisher/files/6165289/WPP-f4e235ad-23f7-4d5c-b776-1a5f55303b3e.log)
this after error

**Comment by DCourtel** [comment]
Hi, error 2149122451 map to «Forbidden (403)». Does your WSUS server need to go through a proxy to reach Internet?
Ensure that WPP and the WSUS service can access Internet.

**Comment by ArielBaravalle** [comment]
> Hi, error 2149122451 map to «Forbidden (403)». Does your WSUS server need to go through a proxy to reach Internet?
> Ensure that WPP and the WSUS service can access Internet.

Hello,   
the serve wsus use a fortigate  to acces to internet. 
but  the error is when I try to create a Update from msi file.   not need iinternet

**Comment by DCourtel** [comment]
Internet access is required for timestamping the CAB file during the signing.

**Comment by ArielBaravalle** [comment]
Yes,  this have internet access,  through a firewall  fortinet

**Comment by DCourtel** [comment]
As per the error message, WSUS doesn’t seem to be able to reach the Internet. Maybe the firewall blocked it or the WSUS service try to bypass the firewall. Could be an authentication issue as well.

**Comment by ArielBaravalle** [comment]
hello @DCourtel ,  thanks for you help
the WSUS work fine ,  and synchronize  without problem  to windows update.  and de WPP is running in the same server.
what connections need open in the firewall to timestamp the CAB  ?

**Comment by DCourtel** [comment]
The WSUS server needs to reach: http://timestamp.digicert.com
Remember that WSUS runs with the System account. So, if your firewall needs authentication, you need to add the computer account in the access right.
You can also disable timestamping to test, by creating a registry key:
![image](https://user-images.githubusercontent.com/13787283/112159388-66024e00-8be9-11eb-92a6-bb2a1fe331f0.png)

**Comment by ArielBaravalle** [comment]
Hello
Work fine !   thanks very much

Regards
