### ISSUE TITLE
Application Not Responding

### ISSUE THREAD

**Issue by Xerionty** [DCourtel/Wsus_Package_Publisher#53]
After successfully connecting to the WSUS server and when creating a new application WPP stops responding:

![image](https://user-images.githubusercontent.com/21998533/112215540-c5c81b80-8c20-11eb-84da-7fa4dfbf693a.png)

Using version 1.4.2103.13 on Server 2012R2. .NET4 is latest. WSUS Version 6.3.9600.18694

**Comment by DCourtel** [comment]
Hi, can you get the log file here: %LocalAppData%\Temp\WPP-GUI.log 
And paste it in here.

**Comment by Xerionty** [comment]
Hi @DCourtel Thanks for replying. I don't have such log in the mentioned folder. However I do have the following logs but those contain sensitive data:

![image](https://user-images.githubusercontent.com/21998533/112372548-3b46f100-8ce0-11eb-99ea-a04b22624eb9.png)

I assume GUI stands for the IDs in my screenshot? What do we particular look for in the logs?

**Comment by DCourtel** [comment]
Delete all WPP logs. Start WPP, try to publish an update, and when it hangs, send the log file.

**Comment by Xerionty** [comment]
I deleted all WPP logs and all of a sudden when I press CTRL+U a new window appears instead of a not responding application. No clue why deleting the logs results into a working application though.

So uhm, it seems the problem got resolved...

**Comment by DCourtel** [comment]
Glad to hear that your issue is solved.
