### ISSUE TITLE
Time stamp problem.

### ISSUE THREAD

**Issue by jurikor** [DCourtel/Wsus_Package_Publisher#54]
Found the following problem.
When I create a new update, the time stamp is set.
If I do "resign" or "revise" the time stamp is not set.

**Comment by DCourtel** [comment]
Hi Jurikor, revising an update only changes metadata, the CAB file is not modified. So the timestamp is preserved if there was one.
Unfortunately, the re-sign operation doesn’t take any parameters. I’m unable to provide a Timestamp server URL when I call the WSUS SDK, so the timestamp is lost!
