### ISSUE TITLE
WPP Crash - File Exstis Rule - Path with Quotation mark

### ISSUE THREAD

**Issue by derDezi** [DCourtel/Wsus_Package_Publisher#55]
Version: 1.4.2103.13

If i put in a Path with Quotation marks in the "File Path" value for the File Exstis Rule WPP crashes. Without the Quotation marks it works fine.

Thank you for your software :)

**Comment by DCourtel** [comment]
Hi derDezi, this error is caused by the WSUS API during the XML validation process. You shouldn’t have to use double quotes in the file path, even if there is spaces in it.
