### ISSUE TITLE
Firefox x86 update package don't work with windows x86 2004 and above

### ISSUE THREAD

**Issue by esbiko13** [DCourtel/Wsus_Package_Publisher#56]
tried to generate firefox update with exe and msi. on windows x86 2004 and above it don't work. with windows x86 1909 there are no problems. No Problems at all with windows x64 1909 and above

Windwos error code : 0x80240017 
Event ID : 20
Windows 10 pro
WPP Release.v1.4.2103.13
WPP Release.v1.4.2008.16
WPP Release.v1.4.1906.3

thanks for your great work 👍

**Comment by DCourtel** [comment]
Hi esbiko13, this error code maps to: Operation was not performed because there are no applicable updates.
How do you make the update? What applicability rules do you declare?

**Comment by esbiko13** [comment]
hey, my traditional way is that i start a custom update to create an install.ini one time. than i create or recreate the update package by extracting the exe file downloaded from mozilla, take the setup.exe and the "core" folder and check the existing file version of installed firefox.exe for installing the new one. i also check the os achitecture (x86 x64) with WMI Query and the presents of the .ini file.
It works fine until windows x86 1909. after upgrading that test vm to 2004 the same update package don't work anymore.
with my x64 windows systems i have no trouble. 

facing this issue today, i also tried to build up the package by the msi version from mozilla and only check the installed product code. same issue x86 don't work x64 works fine. :(

**Comment by DCourtel** [comment]
What happens if you try to run the EXE manually on the client computer? Does it upgrade?

**Comment by esbiko13** [comment]
yes, manual install works

**Comment by DCourtel** [comment]
Can you try to pull out the WMI  OS architecture query and replace it with a classic OS architecture in WPP?
![image](https://user-images.githubusercontent.com/13787283/117453646-77a77700-af45-11eb-922e-fedc625cf3d0.png)

**Comment by esbiko13** [comment]
Hey David, that works! Replacing WMI with Processor Architecture makes the update work again!

Thanks !!!
