### ISSUE TITLE
Import an entire update or rules from a single file

### ISSUE THREAD

**Issue by tb-mtg** [DCourtel/Wsus_Package_Publisher#57]
Currently there is the ability to save & load rules individually for both **installed** & **installable** rules.

Is there any way to import both from a combined single xml file?

An example could be something like below which would update _**Notepad++ 64bit (English)**_:

```
<IsInstalled>  
  <lar:And>
    <bar:Processor Architecture="9"/>
    <bar:WindowsLanguage Language="en"/>
    <bar:RegSzToVersion Key="HKEY_LOCAL_MACHINE" Subkey="SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Notepad++" Value="DisplayVersion" Comparison="EqualTo" Data="7.9.5.0"/>
  </lar:And>
</IsInstalled>  
<IsInstallable>  
  <lar:And>
    <bar:Processor Architecture="9"/>
    <bar:WindowsLanguage Language="en"/>
    <bar:RegSzToVersion Key="HKEY_LOCAL_MACHINE" Subkey="SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Notepad++" Value="DisplayVersion" Comparison="GreaterThan" Data="0.0.0.0"/>
    <bar:RegSzToVersion Key="HKEY_LOCAL_MACHINE" Subkey="SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Notepad++" Value="DisplayVersion" Comparison="LessThan" Data="7.9.5.0"/>
  </lar:And>
</IsInstallable>  
```
The example above is inspired from the WSUS 3.0 Class Library [**Version Detection Logic**](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/bb902489(v=vs.85)) and [**Update Applicability Rules**](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/bb902473(v=vs.85)) pages which are no longer updated.

However I notice that the [Windows Server Update Services 3.0 Class Library](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ms744624(v=vs.85)) is being referenced in project [WPP.Wsus.csproj](https://github.com/DCourtel/Wsus_Package_Publisher/blob/a6df2c40c104afc02890314aae7c8a2d0f9fa1f7/code/WsusAD%20Comparator/WPP.Wsus/WPP.Wsus.csproj#L37).

**Comment by DCourtel** [comment]
Hi tb-mtg, right now there is no way to import both in one step. You have to import it separately.
