### ISSUE TITLE
Telemetry info being shared

### ISSUE THREAD

**Issue by BTruthful** [DCourtel/Wsus_Package_Publisher#58]
Anybody care to comment why WPP is sending telemetry data back to the wpp website?

wsus server id, client quantity, client os list, ip, domain name, etc.

Please make this optional in the next release.

**Comment by DCourtel** [comment]
Hi BTruthful, WPP send back telemetry to get a better understanding of where it is used. We collect technical information like Windows version, WSUS version, WPP version… to prepare for WPP v2.
None of this information is shared with anybody.
