### ISSUE TITLE
How can I share my WPP configs and Updates?

### ISSUE THREAD

**Issue by MarcelHillmann** [DCourtel/Wsus_Package_Publisher#59]
Hi,

I would like to share my updates with my colleagues, is that possible?
Are there some planes to integrate GIT to archive the workspace?

Thx Marcel

**Comment by DCourtel** [comment]
Hi MarcelHillmann, that’s not very easy. The only way I see is to have the WSUS server of your colleagues be a downstream server of yours. In this case, the downstream server must trust the code-signing certificate use to sign the CAB files.

**Comment by MarcelHillmann** [comment]
Hi,

sorry that was a misunderstanding. 
We working both on the same WSUS server but with different Windows Profiles.

I couldn’t see his workspace meta data.

thx Marcel

**Comment by DCourtel** [comment]
What do you mean by workspace metadata?
If from one WPP instance you don’t see updates that have been published by the other instance, be sure to have the «Show Locally-Published updates that are also visible in WSUS console» checked in Tools -> Settings -> Updates

**Comment by MarcelHillmann** [comment]
Hi,

what I mein is That you Store everything to „ System.Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments, Environment.SpecialFolderOption.None)“

Is it possible to use a alternative path?
We would like to see the Update Definition on the same Server from each other.

thx Marcel

**Comment by DCourtel** [comment]
Hi MarcellHillmann, I’m surprised because WPP doesn’t store anything in the «My Documents» folder. Can you share a screenshot of what you are seeing from WPP in that folder?
Thanks.
