### ISSUE TITLE
WPP not importing Reader or Flash Updates

### ISSUE THREAD

**Issue by 54rd3** [DCourtel/Wsus_Package_Publisher#6]
Hi, i'm using WWP for years now an suddenly it stopped importing new Updates from Catalogue.  The Import procedure does not show any error, but no new updates are not showing up in WPP Console.
Custom Java Packages work fine just like ever.
W2k12 R2 Server, WSUS Version 6.3.9600.18833 and WPP 1.3.1702.10
Cert still good until 2021. 

Anybody can help? 

Edit: New Version WPP 1.4.1906.3 does not help. Same issue

**Comment by DCourtel** [comment]
Hi, do you see any error messages in the log file of WPP? %temp%\wpp-GUID.log

**Comment by 54rd3** [comment]
Hi, here's the log file. i could not find anything. maybe you check

thanks

Am Do., 6. Juni 2019 um 16:55 Uhr schrieb David COURTEL <
notifications@github.com>:

**Comment by DCourtel** [comment]
I can't see any log file in your post.
Yesterday, I have tried to publish Adobe Reader and Flash player from the catalog. The updates were published without any problems.

**Comment by dwydler** [comment]
We have with the new version the same problems. A rollback to the prev version of wpp brought nothing.
Environment: Windows Server 2012R2 Standard with WSUS and SQL Server Express. Patchlevel: April 19.

**Comment by DCourtel** [comment]
Does it work with other catalogs?

**Comment by dwydler** [comment]
We have only Adobe Acrobat XI, Adobe Reader DC and Adobe Flashplayer Catalogs in use.
All have the same problem. If tell me other catalogs i will test these.

**Comment by DCourtel** [comment]
I don't have a repro. Can you look at the log file?

**Comment by 54rd3** [comment]
Ok, here is the log.

**Comment by DCourtel** [comment]
06.06.2019 17:10:21	Will try to publish : Adobe Acrobat Reader DC - MUI Update 15.006.30497
06.06.2019 17:10:21	The update already exists.

**Comment by dwydler** [comment]
I reproduce the issue with Adobe Flash Player today.
Can you tell me email address? I will send you the files (screenshots and logfilee on private way because I saw private data in the logfile.

**Comment by 54rd3** [comment]
Hi,
Thats what i mentioned before. The files are downloading and say importing but are NOT showing up in list. 
see attached screenshots.
So how can i approve updates if not showing up in List?
any suggestions?
![Katalog png](https://user-images.githubusercontent.com/51449802/59338246-5494ce00-8d02-11e9-8ca7-6d6f30a5a63b.jpg)
![List png](https://user-images.githubusercontent.com/51449802/59338282-64acad80-8d02-11e9-9079-45cdc3cce02e.jpg)

thanx

**Comment by DCourtel** [comment]
Can you go into Settings and verify that this option is enabled
![WPP_Option](https://user-images.githubusercontent.com/13787283/59341800-cbcd6080-8d08-11e9-8f0b-4033f8b118a9.png)
:

**Comment by 54rd3** [comment]
That did it.
 But it made me a new UpdateGroup (Adobe). I had only 2 groups now three.  Not really a problem.

Thank you very much.

 
![image](https://user-images.githubusercontent.com/51449802/59345093-b0198880-8d0f-11e9-9fc0-156af44117ad.png)

**Comment by 54rd3** [comment]
should i close issue?
