### ISSUE TITLE
Detect both per-User & per-machine installations

### ISSUE THREAD

**Issue by tb-mtg** [DCourtel/Wsus_Package_Publisher#60]
By default Microsoft's OneDrive is installed **per-user** into folders like below:

> C:\Users\\**{user-name}**\AppData\Local\Microsoft\OneDrive\\**{version}**\OneDriveSetup.exe

We want to detect and replace these with **per-machine** installations.
This is possible using arguments **/silent /allusers** which installs into a single folder like below:

> C:\\**Program Files**\Microsoft OneDrive\\*{version}*\OneDriveSetup.exe

I have tried using **FileExists** with wildcards in the path as the _"Is Installable"_ rules but it did not work:
```
<lar:And>
  <bar:Processor Architecture="9"/>
  <lar:Or>
    <lar:And>
      <bar:RegSzToVersion Key="HKEY_LOCAL_MACHINE" Subkey="SOFTWARE\Microsoft\OneDrive" Value="Version" Comparison="GreaterThan" Data="0.0.0.0"/>
      <bar:RegSzToVersion Key="HKEY_LOCAL_MACHINE" Subkey="SOFTWARE\Microsoft\OneDrive" Value="Version" Comparison="LessThan" Data="21.119.613.1"/>
    </lar:And>
    <bar:FileExists Path="C:\users\*\AppData\Local\Microsoft\OneDrive\*\OneDriveSetup.exe"/>
  </lar:Or>
</lar:And>
```
It does detect if previous per-machine versions are installed, but is does not detect per-user installations.

So my questions are:

* Is there any way to detect if something has been installed per-user rather than per-machine?

* When using the **FileExists** rule, can wildcards be used as shown like below?

> C:\users\\*\Admin\AppData\Local\Microsoft\OneDrive\

**Comment by DCourtel** [comment]
Hi tb-mtg, to my knowledge, the FileExists element doesn’t support wildcard characters. Managing per-user applications can be tough, especially since Windows 10.

**Comment by johnripper1** [comment]
In short (to answer your question):
* as Wildcard is not supported.
Using "username" or anything else will not help either, as the install is run per system

In long (i dont understand your requirement to detect something in a user folder):
a)
In standard settings OneDrive installs in the users folders. But the install file is on  %progamFilesx86%\Microsoft OneDrive
So there is no need to detect something (file or version number) in any user folder, as OneDrive has an autoinstall to keep the software up to date as required. You should not overwrite the autoinstaller, as this will cause problems on a long run, if you dont update OneDrive on a regular basis.
If you want to make sure the computer is "ready" to have OneDrive for the next user setup use the path above to detect.
Beside this, the solution doesnt make sense as more user profile live on that computer. Think about certain TS.
Expections for very specific szenarios may apply.

b)
If you want to make sure a certain version is installed, join the corresponding update ring, using GPO:
https://support.microsoft.com/en-us/office/onedrive-release-notes-845dcf18-f921-435e-bf28-4e24b95e5fc0

c)
I would suggest to install as per machine. Using /silent /allusers (as stated above) will replace the user installtion.
For me, there is no reason to not do it so.

Taking about expections: Using a machine installer, will solve that problem, as it is easy to detect a file & version very easily. Keep in mind, that x64 and x32 installed as required per machine....

**Comment by tb-mtg** [comment]
@johnripper1 

> In long (i dont understand your requirement to detect something in a user folder):

We want to replace **per-user** with **per-machine** installations, but **only** on machines that have installations in any user's folder.  

So if a machine has no per-user installations detected at all - we do not need to install it per-machine on that device.

**Comment by johnripper1** [comment]
> So if a machine has no per-user installations detected at all - we do not need to install it per-machine on that device.

Can I ask why? Maybe there is another solution...

**Comment by tb-mtg** [comment]
@johnripper1 We only want replace the per-user installations with per-machine installations - not introduce new installations on machines where it is not used/required.

**Comment by johnripper1** [comment]
Sorry, this doesnt make sense to me.

Normally you should know the computer MS Teams should run on (either has been or could be). Then create a GPO and target it to these computer.

BTW: For me it seams to be more compliacted to seperate those computer MS Teams is installed from those not installed, instead of just rolling this out to all.

**Comment by tb-mtg** [comment]
@johnripper1 I never mentioned MS Teams, I mentioned OneDrive. 

Regardless of which application, OneDrive was just used as an example to see if it were possible to detect **per-user** installations.

**Comment by johnripper1** [comment]
As you said, the app doesnt make a difference.

I you cant achive this with WSUS out of the box. But maybe some script could make it. Detect all %user% folders and then search for the resp. exe/msi.
