### ISSUE TITLE
MSI Parameters not being sent to msiexec.exe

### ISSUE THREAD

**Issue by LFM8787** [DCourtel/Wsus_Package_Publisher#61]
Hi! I´ve been using WSUS Package Publisher and it´s such a piece of software, congratulations!

After several tests trying to embeed a .mst file using TRANSFORMS=file.mst as a parameter in a custom action and checking the log, came to the conclussion that there was something wrong in the code...

https://github.com/DCourtel/Wsus_Package_Publisher/blob/a6df2c40c104afc02890314aae7c8a2d0f9fa1f7/code/CustomUpdateEngine/Actions/InstallMsiAction.cs#L65

The parameters are not being sent to msiexec.exe

**Comment by jayseeem** [comment]
Just ran into the pesky bugger today! Should have checked here first.

+1 for fix.

Version: 1.4.2103.13

**Comment by DCourtel** [comment]
Fix in 1.4.2204.9
