### ISSUE TITLE
Failed to sign package

### ISSUE THREAD

**Issue by StadtBadWurzach** [DCourtel/Wsus_Package_Publisher#62]
Hi Guys,
i updated to the newst version of wpp. After that i try to import a new exe application.
But on the of status bar (100%) i get follow error:
![image](https://user-images.githubusercontent.com/43094829/126606824-141699da-3a01-4d8d-9ad0-95fcdbba4d1d.png)

![image](https://user-images.githubusercontent.com/43094829/126606851-273cb1af-25bd-4b99-b0bc-40ad91b7dd37.png)

WSUS and WPP are on the same vm. The SSL Certificate is valid till 2025.

I tried follow things:
- restart hole server - no success
- Import the self-signed certificate in wpp - no success
- Try to create another package - same error.

What means the error 2149122451?

**Comment by DCourtel** [comment]
Hi StadtBadWurzach, please take a look at this thread: https://github.com/DCourtel/Wsus_Package_Publisher/issues/52

**Comment by StadtBadWurzach** [comment]
Thanks. That's solved the problem.

**Comment by StadtBadWurzach** [comment]
Thanks. That's solved the problem.
