### ISSUE TITLE
Packages wont Install on Client

### ISSUE THREAD

**Issue by KenjiOrigin** [DCourtel/Wsus_Package_Publisher#63]
Hello,

I have started in a new company and wanted to introduce some Update System with WSUS + WPP.

So, WSUS is runnin and the WPP as well, my Computer is recognized as a Client. 

I have packed an "Update" to install "7-Zip" on my Test Client. 
I had some trouble with the error Message "Can not Copy the File" - but somehow i fixed it.

But now i have the Problem that the WPP is saying "Status: Sending Command" - this goes for like 2 Minutes and than its gone... but nothing happend.

I have WPP Installed locally on the WSUS. Have tried it with Local Admin and a Domain admin (which I added to the WSUS-Administrator group).
The Certificate is installed on both, server and client and I have made the Changes to the GPO. 

So far I am kinda clueless how to move on :(

Any kind of help is appreciated - and if I missed some important information i will give it to you :)

**Comment by DCourtel** [comment]
Do clients report the update as not installed?
