### ISSUE TITLE
Failed to sign package; error was: 2147954402

### ISSUE THREAD

**Issue by ljbrusta** [DCourtel/Wsus_Package_Publisher#64]
Trying to publish a simple package and receive error: Operation Failed with Error: Failed to sign package; error was: 2147954402
from the %LocalAppData%\Temp log file I see this.
**** System.InvalidOperationException : Failed to sign package; error was: 2147954402

I see a closed issue where it said "Also, ensure your WSUS server can access Internet to use the timestamping option."
We are in a very locked down environment and use a proxy server whitelist to only allow Microsoft update catalog connections. So I'm not sure what this is referring to. Being that this systems is pretty much air gapped is there another option to fix this?

Running WPP v1.4.2103.13 on the internal WSUS 2016 server with an Internal Microsoft Enterprise CA for the code signing certificate.

**Comment by DCourtel** [comment]
Hi ljbrusta, can you create a Reg_SZ value in HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\EasyCompany\Wsus Package Publisher with the data = 1 and try again. That will disable timestamping from WPP.

**Comment by ljbrusta** [comment]
Just any value name for the Reg_SZ?

**Comment by DCourtel** [comment]
Sorry, I forgot the value name: DisableTimestamping
