### ISSUE TITLE
Enhancements request: append function in Templates

### ISSUE THREAD

**Issue by LFM8787** [DCourtel/Wsus_Package_Publisher#65]
Hi there, I've been using WPP and I like it a lot.

It could be great that among the current options for templates, there was an Append options:
![image](https://user-images.githubusercontent.com/13755139/129562415-09e456cc-65d7-4755-81f6-dabfb54618a6.png)

So, when importing a .CustAct file it doesn't replace all the actions.

**Comment by DCourtel** [comment]
Added in 1.4.2204.9
