### ISSUE TITLE
Enhancements request: expand parameters

### ISSUE THREAD

**Issue by LFM8787** [DCourtel/Wsus_Package_Publisher#66]
Hi there, if there any chance to implement parameter expansion?

Example:
![image](https://user-images.githubusercontent.com/13755139/129625280-3072656a-7d25-448a-9350-f7ba3f5a8516.png)

Source action file:
`CustomUpdate Version="2">
<Action>
<ElementType>CustomActions.ExecutableAction</ElementType>
<PathToTheFile>gimp-2.10.24-setup-3.exe</PathToTheFile>
<Parameters>/DIR="%ProgramFiles%\GIMP"</Parameters>
<KillProcess>True</KillProcess>
<DelayBeforeKilling>10</DelayBeforeKilling>
<StoreToVariable>True</StoreToVariable>
</Action>
<Action>
<ElementType>CustomActions.ReturnCode</ElementType>
<Method>Variable</Method>
</Action>
</CustomUpdate>`

**Comment by DCourtel** [comment]
Fix in 1.4.2204.9
