### ISSUE TITLE
XML bug: not escaping prohibited characters

### ISSUE THREAD

**Issue by LFM8787** [DCourtel/Wsus_Package_Publisher#67]
Hi there, when creating custom actions the Custom Update Creator save the file (XML as CusAct) with prohibited characters that then fails when trying to load or execute with CustomUpdateEngine.exe.

![image](https://user-images.githubusercontent.com/13755139/130777834-91241212-13d8-41a2-9f30-01cb578aab60.png)
When trying to load a recently created action with '&'...

The file content:
`<CustomUpdate Version="2">
<Action>
<ElementType>CustomActions.ExecutableAction</ElementType>
<PathToTheFile>%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe</PathToTheFile>
<Parameters>-NoProfile -NoLogo -NonInteractive -ExecutionPolicy Bypass -command "&{#some commands}"</Parameters>
<KillProcess>True</KillProcess>
<DelayBeforeKilling>1</DelayBeforeKilling>
<StoreToVariable>False</StoreToVariable>
</Action>
<Action>
<ElementType>CustomActions.ReturnCode</ElementType>
<Method>Variable</Method>
</Action>
</CustomUpdate>`

If I use escaped characters everything works well.

Thank you!

**Comment by DCourtel** [comment]
Fix in 1.4.2204.9
