### ISSUE TITLE
"create directory failed" by Create an Update

### ISSUE THREAD

**Issue by derToWa** [DCourtel/Wsus_Package_Publisher#69]
Hello,
I'm try to use WPP on my HomeLab but I can't create an update.

- Server 2019 Essentials with WSUS
- ContentDir Registry E:\WSUS\
- UpdateServicesPackages available
- WsusContent available
- Rights checked on the shares and also NTFS
- SelfSigned Certificate from WPP

![027d915dc8eb49580ff40dc246227d97](https://user-images.githubusercontent.com/61687029/137396463-544ca9cb-294e-4441-872d-cbf0a170eb35.jpg)

Is there anything else I can do?

Many thanks
ToWa

**Comment by DCourtel** [comment]
Hi, can you check this KB: [Create Directory Failed](https://patchmypc.com/an-error-occurred-while-publishing-an-update-to-wsus-createdirectory-failed)

**Comment by derToWa** [comment]
Many thanks for our reply but there is nothing different. :(

Step 1:
- [x] WSUS Content Shared Directories Exist
- [x] Folder paths exist and match
Step 2:
- [x] Full allow permissions on share for NETWORK SERVICE, WSUS Administrators, and Administrators
- [x] Full allow NTFS permissions for SYSTEM, NETWORK SERVICE, WSUS Administrators, Administrators
Step 3:
- [x] Validate the WSUS Content Folder in the Registry Matches the SUSDB

**Comment by MrChance1985** [comment]
I have the same issues with a Windows 2019 Installation. I  have tried everything from the KB.

**Comment by derToWa** [comment]
Hey again,
same problem with another enviroment.
- Server 2019 Datacenter DC (Core)
- Server 2019 Datacenter (GUI) with WSUS

Everything from the KB is fine.
Is there any logfile or option to find out what does the "CreateDirectory failed" message means?

**Comment by DCourtel** [comment]
I updated WPP to log the Native Error Code when this error happens. Hopefully, it will give us more info on the origin of this issue.

**Comment by derToWa** [comment]
> I updated WPP to log the Native Error Code when this error happens. Hopefully, it will give us more info on the origin of this issue.

Many thanks.
Is that active in release v1.4.2103.13?
Because I din't get any other Error on publishing. :(

**Comment by DCourtel** [comment]
No, it’s on 1.4.2203.16. You should receive the update next time WPP auto-update. If not, contact me.

**Comment by derToWa** [comment]
Hey,
I've installed 1.4.2203.19 and now I get:

- CreateDirectory failed [1326]

what does error code 1326 means?

**Comment by DCourtel** [comment]
Hey derToWa, this error code maps to «Incorrect username or password» [Source: Windows]. Does the directory hosted on a remote server or a NAS? Is it a shared folder connected through a network drive?

**Comment by MrChance1985** [comment]
Hello @DCourtel
I have the same error. My case is: i have everything on the local drive installed (WSUS Server + WPP).

**Comment by derToWa** [comment]
Hey @DCourtel 
There is and there was no NAS or other network storage in use. :(
I try to publish a MSI from local drive to WSUS on local drive. 

I had two systems with these errors. One system (2019 Essentials) I reinstalled a few weeks ago and tried to use WSUS publisher directly. It works perfectly so a solution is to reinstall the server OS. :-D

**Comment by DCourtel** [comment]
Do you have these KBs installed? KB5011486 or KB5010419

**Comment by MrChance1985** [comment]
> Do you have these KBs installed? KB5011486 or KB5010419

I don't have any of the KB installed.

**Comment by derToWa** [comment]
> Do you have these KBs installed? KB5011486 or KB5010419

Sorry these KBs are for systems up to 2012 R2 but I've Server 2019 running so these KBs aren't available for me.

**Comment by DCourtel** [comment]
MrChance1985, can you ensure to use the latest release of WPP (1.4.2203.19) and try again. You should have an error code in the log that should tell us more about the origin of the issue.

**Comment by MrChance1985** [comment]
> MrChance1985, can you ensure to use the latest release of WPP (1.4.2203.19) and try again. You should have an error code in the log that should tell us more about the origin of the issue.

Thanks for the response
I forget to mention. I have the same Error as @derToWa  ( error code 1326 ). Unfortunately i can't reinstall Windows as him.

**Comment by DCourtel** [comment]
Can you open the log file. It should be in %LocalAppData%\Temp and the name of the file is WPP-_GUID_.log
You should be able to see a line starting by **** Win32Exception
and then an error message and the error code 1326.
Can you copy/paste that line here?

**Comment by derToWa** [comment]
@DCourtel 

> 04.04.2022 07:51:19	Starting. Release : 1.4.2203.19
> 04.04.2022 07:54:59	**** System.ComponentModel.Win32Exception : CreateDirectory failed [1326]

I can see that WPP creates temporary folders under %LocalAppData%\Temp\WPP\ for every try with my MSI and an XML.
Log file attached.
[WPP-f0e81ec2-9aed-42c7-9e7f-2c778ee8adca.log](https://github.com/DCourtel/Wsus_Package_Publisher/files/8407058/WPP-f0e81ec2-9aed-42c7-9e7f-2c778ee8adca.log)

**Comment by MrChance1985** [comment]
Here ist a cut from my Log if it helps it is different from derToWA:
 xmlns="http://www.w3.org/2001/XMLSchema"
 xmlns:bar="http://schemas.microsoft.com/wsus/2005/04/CorporatePublishing/BaseApplicabilityRules.xsd"
 xmlns:bt="http://schemas.microsoft.com/wsus/2005/04/CorporatePublishing/BaseTypes.xsd"
 xmlns:cmd="http://schemas.microsoft.com/wsus/2005/04/CorporatePublishing/Installers/CommandLineInstallation.xsd"
 xmlns:lar="http://schemas.microsoft.com/wsus/2005/04/CorporatePublishing/LogicalApplicabilityRules.xsd"
 xmlns:msi="http://schemas.microsoft.com/wsus/2005/04/CorporatePublishing/Installers/MsiInstallation.xsd"
 xmlns:msiar="http://schemas.microsoft.com/wsus/2005/04/CorporatePublishing/MsiApplicabilityRules.xsd"
 xmlns:msp="http://schemas.microsoft.com/wsus/2005/04/CorporatePublishing/Installers/MspInstallation.xsd"
 xmlns:sdp="http://schemas.microsoft.com/wsus/2005/04/CorporatePublishing/SoftwareDistributionPackage.xsd"
 xmlns:uei="http://schemas.microsoft.com/wsus/2005/04/CorporatePublishing/Installers/UpdateExeInstallation.xsd"
 xmlns:usp="http://schemas.microsoft.com/wsus/2005/04/CorporatePublishing/UpdateServicesPackage.xsd"
 xmlns:drv="http://schemas.microsoft.com/wsus/2005/04/CorporatePublishing/Installers/WindowsDriver.xsd"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  SchemaVersion="1.2"><sdp:Properties PackageID="23882bc6-ff5a-4e24-bca8-cb6c30265ce1" CreationDate="2022-03-21T14:45:24.763Z" VendorName="Next Generation Software" PublicationState="Published" CanSourceBeRequired="false" UpdateType="Software"><sdp:ProductName>Next Generation Software</sdp:ProductName></sdp:Properties><sdp:LocalizedProperties><sdp:Language>en</sdp:Language><sdp:Title>mRemoteNG (64 bit)</sdp:Title><sdp:Description>No description available.</sdp:Description></sdp:LocalizedProperties><sdp:ApplicationSpecificData /><sdp:IsInstallable><bar:FileExists Path="C:\Program Files\Notepad++"/></sdp:IsInstallable><sdp:IsInstalled><bar:FileExists Path="C:\Program Files\Notepad++"/></sdp:IsInstalled><sdp:InstallableItem ID="1f9ddcee-8da8-42fa-80a6-44f6d135e0fc" ><sdp:ApplicabilityRules><sdp:IsInstalled><msiar:MsiApplicationInstalled/></sdp:IsInstalled><sdp:IsSuperseded><msiar:MsiApplicationSuperseded /></sdp:IsSuperseded><sdp:IsInstallable><msiar:MsiApplicationInstallable/></sdp:IsInstallable><sdp:Metadata><msiar:MsiApplicationMetadata><msiar:ProductCode>{dba343f4-d6c4-4b60-8188-5c10d7f011f7}</msiar:ProductCode></msiar:MsiApplicationMetadata></sdp:Metadata></sdp:ApplicabilityRules><sdp:InstallProperties CanRequestUserInput="false" RequiresNetworkConnectivity="false" Impact="Normal" RebootBehavior="CanRequestReboot" /><sdp:UninstallProperties CanRequestUserInput="false" RequiresNetworkConnectivity="false" Impact="Normal" RebootBehavior="CanRequestReboot" /><msi:MsiInstallerData ProductCode="{dba343f4-d6c4-4b60-8188-5c10d7f011f7}" MsiFile="2022.01.07-1.77.2-nb.mRemoteNG-Installer.msi"/></sdp:InstallableItem></sdp:SoftwareDistributionPackage>

3/21/2022 3:45:24 PM	**** System.ComponentModel.Win32Exception : CreateDirectory failed [1326]
3/21/2022 3:45:28 PM	Entering Void btnOk_Click(System.Object, System.EventArgs)
3/21/2022 3:45:28 PM	Entering Void Close(System.Object, System.EventArgs)
3/21/2022 3:46:09 PM	Entering Void FrmWsusPackagePublisher_FormClosing(System.Object, System.Windows.Forms.FormClosingEventArgs)

**Comment by DCourtel** [comment]
Ok, nothing new. 
The only thing I can say is that WSUS calls the CreateDirectory function in Kernel32.dll and that function returns the error code 1326 which maps to «Incorrect username or password». As the error occurs in the Kernel32.dll, it is out of the scope of WPP.
