### ISSUE TITLE
Issue while deploying Custom Update with version 1.4.1904.29

### ISSUE THREAD

**Issue by Abstremik** [DCourtel/Wsus_Package_Publisher#7]
Hello,

I've recently encountered the following problem with the current version of WPP.

When deploying a custom update I am running into an "FFFE error" on wsus client machine.

The CustomUpdate was defined with a ExecuteElement to simply run a cmd file. The file was provided by me among a few others. This allowed me to make some registry changes and update Google Chrome browser along with some custom settings.

This mechanism worked fine with the previous WPP but seems to be failing with the current version.

Thanks.

**Comment by DCourtel** [comment]
Please, delete all CustomUpdate created with the v1.4.1904.29 release, and re-create it with Release v1.4.1906.3.

**Comment by Abstremik** [comment]
Just tested and it looks fine.
Thanks for your help.
