### ISSUE TITLE
WPP V2

### ISSUE THREAD

**Issue by admedv** [DCourtel/Wsus_Package_Publisher#70]
Hello,

since many years I am using WPP for publishing several software in our domains.

Unfortunately th current version is not supporting Win10 and Server 2019 fully (means no way to do a pull request cause wuaclt is replaced by usoclient).

Now me (and i guess many others) are waiting for the new version of WPP.
I know this is a project that you (=DCourtel) do beside ur job .. and I not want to force in any way ... but I'm courious for the new release ... WPP v2.0.1

Thank you for this great tool.

**Comment by StyleTec** [comment]
A while ago I offered my help in contributing to this project by doing development. But never got an answer.
As the source code for this project is private, this might be a reason for this.

**Comment by DCourtel** [comment]
Thank you admedv for using WPP for so long. I know that WPP is pretty old now and the new usoclient doesn’t help! The MS SDK for WSUS is still written in .Net 4.5 and doesn’t feat very well with modern technology. But, I’m still working on a v2.
StyleTec, sorry if I didn’t answer your request. It probably fell at the wrong time.
