### ISSUE TITLE
Bypass proxy for local IPs

### ISSUE THREAD

**Issue by s0bm9928** [DCourtel/Wsus_Package_Publisher#71]
WPP seems to use the proxy server for all HTTP connections -  even for the local WSUS server. Can an option be added to list IPs and/or URLs that bypass the proxy, similar to how a web browser is configured?

**Comment by DCourtel** [comment]
WPP uses the proxy only to download or upload things from the Internet, not to communicate with WSUS. Can you be more precise on what connections go through the proxy?

**Comment by s0bm9928** [comment]
When publishing a package from WPP to WSUS I see a lot of http traffic hitting the proxy destined for WSUS. I thought WPP uses a direct SQL connection to the WSUS database and not http. But from the proxy logs it looks like a lot of http.

**Comment by DCourtel** [comment]
That’s weird. All connections use the SDK, which doesn’t account for the proxy. 
Do you have declared a proxy in IE settings at System level?

**Comment by s0bm9928** [comment]
No

**Comment by DCourtel** [comment]
WPP is installed on a remote computer or directly on the WSUS server?

**Comment by s0bm9928** [comment]
On the WSUS server.

**Comment by DCourtel** [comment]
What happens if you remove the proxy from WPP settings?

**Comment by s0bm9928** [comment]
Then I don't see http traffic hitting the proxy bound for WSUS. But then I obviously can't download Adobe updates.

**Comment by DCourtel** [comment]
WPP uses the proxy only to download binaries from the Internet when publishing updates from a catalog.
Can you try to make a network capture with Wireshark or another tool and send me that over?
