### ISSUE TITLE
Wiki Pre-requisites Update

### ISSUE THREAD

**Issue by Dalacor** [DCourtel/Wsus_Package_Publisher#72]
I started using WSUS Package Publisher many years ago. The instructions years ago suggested that I needed to open File and Printer sharing port on W7/W10 client computers for WSUS Package Publisher to update clients. Unfortunately I cannot find the original documentation as the website it was hosted on no longer exists. I don't know if the documentation was wrong or the program was updated to no longer require this?

The current wiki guide provides no information on what firewall ports if any need to be opened for clients or servers or whether this is dependent on WSUS Package Publisher version?

I would really love to disable File and Printer sharing on the W10 client computers as I have never been happy with the huge security hole that this creates. So it would be helpful if it was very clear in the wiki guide, what firewall ports need to be opened and where.

Otherwise the program works flawlessly and has never given me any issues. Thank you.

**Comment by DCourtel** [comment]
You can close those ports on clients' side. There were required for some right-click options to interact with remote computers. With the new WUA on Windows 10, that does work anymore.

**Comment by Dalacor** [comment]
Thank you for confirming. I have already managed to test the settings as I was setting up a new network and can confirm that I don't need any firewall rules for either client or servers to make WSUS Package Publisher work. Any rules required are configured when installing WSUS on the server.

Brilliant to be able to finally close that Firewall security hole as File and Printer services is a big security issue.

Many thanks
