### ISSUE TITLE
Downstream servers, do not recieve files added frm WPP.

### ISSUE THREAD

**Issue by kpcz** [DCourtel/Wsus_Package_Publisher#73]
Hi.
 On main WSUS server everything works great. But when publishing update, on downstream server the update file is missing (Folder in WPP GUI is in red color) and no file is present in WSUSContent\XX\ directory on downstream server (just empty folder) 

Should I some how manually sync downstream servers, or there is some issue with WSUS server that it is not syncing all WSUSContent dir? 

Or what ports must be opened between server and downstream servers. Did not find any in wiki.

Nothing useful in logs, don't have any clue where to search further.

**Comment by DCourtel** [comment]
Can you check that the downstream server trusts the code signing certificate used by the upstream server?
