### ISSUE TITLE
Implementing WPP

### ISSUE THREAD

**Issue by rybsonldz** [DCourtel/Wsus_Package_Publisher#74]
Hello,

Just a quick question, is it normal that virustotal marks potential danger in that package?
![image](https://user-images.githubusercontent.com/74710625/158188805-1efdc6e1-a62c-4e9c-b827-14f5db53d7ae.png)

https://www.virustotal.com/gui/file/ddac1c8e70867e3833e9df11a4d7836679c779c01a16510e39eda2c8347faf18

I would love not to infect the whole company because of that 🥇

**Comment by DCourtel** [comment]
Hi rybsonldz, unfortunately…yes. WPP has some EXE that triggers alerts based on behavior. But WPP is widely used in the community without any issue.
