### ISSUE TITLE
Uninstall MSI Product not functional

### ISSUE THREAD

**Issue by gruppenrichtlinien** [DCourtel/Wsus_Package_Publisher#75]
Hi David,

The Client does not start the update. It is approved to the clients group, I tried "All Computers" aswell.

I tried different ways to uninstall an MSI with WPP. Decline did not work, so I created a Custom Update and tried 4 different methods:
Uninstall by GUID, Uninstall by Name, Run Executable und create a checkfile and at last, all of them :-)
I tried with and without "{," "}" ...
[bddb0cfc-a330-4d50-bd52-0b88cd803aef.txt](https://github.com/DCourtel/Wsus_Package_Publisher/files/8453492/bddb0cfc-a330-4d50-bd52-0b88cd803aef.txt)

Within WPP my rules are: Already Installed = if checkfile exist, Installable = if MSI Product GUID of Uninstall App  exist.
I tried with and without Rules.

My XML attached

**Comment by DCourtel** [comment]
If you have deployed the MSI through WSUS and a regular update, just approve the update for uninstallation. If the MSI was deployed through a custom update, decline it. Then, make a new update with the MSI and approve it for uninstallation.

**Comment by gruppenrichtlinien** [comment]
That´s what I did in first try, because it wasn´t removed I tried the different ways.

I will check again. Thanks!

EDIT: Sorry, David, my fault. Please delete the issue. I used a newly installed computer for testing and it wasn´t in any of the groups, it belongs to. PEBCAK.

**Comment by gruppenrichtlinien** [comment]
I have still a problem uninstalling any installed MSI. I took a manually installed MSI and want to uninstall it by custom action. 
Manually uninstall from CMD is successful: msiexec /x {5B902003-C0C1-4C4D-956E-C3C12ED7C14D} /qn /norestart

The updates run always 100% without error, but do not execute the uninstall. 

Tests:
Uninstall by GUID, Uninstall by ExecuteFile (msiexec with and without path), Uninstall by Powershell Script.

**Comment by gruppenrichtlinien** [comment]
After testing the whole afternoon I am at the end with my ideas. 

The only funtional custom action is "Folder Deletion" combined with Installable Rule "File Exists".

As soon there is a GUID or an Execute File it gets broken.
- Add "Delete Regkey" HKLM\...\CurrentVersion\Uninstall\{5B902003-C0C1-4C4D-956E-C3C12ED7C14D}
--> Delete Folder no longer functional
- Add Installable Rule "MSI Exist" and add GUID 
--> Delete Folder no longer functional

Deploy MSI and directly use "Approve for Uninstallation does not work either. The Application is not recognized by WUpdate Agent. The Remote Install Manager can only find my MSI with the specific GUID if it is installed locally.

In every test, where I call a commandline, Wupdate shows the update, complete 100% without error, but it seems nt to execute.
Tried even to call the MSI from UNC again, without any luck.
msiexec /x \\wsus\wsuscontent\_WPPCustomUpdate\MyApp\MyApp.msi /qn
(inside _WPPCustomUpdate are some other deployments, simple copy jobs, they are functional)

Running on Version 1.4.2203.9

LAST TRY, functional
- Custom Action: Install MSI 
- NOW! Custom Action: Uninstall by GUID is functional
-> Install same MSI manually again
--> Custom Action: Uninstall by GUID is NOT functional, Wupdate runs 100%, but doesn´t remove my app

The question is: How to control software not deployed by WPP?
