### ISSUE TITLE
Question no Issue

### ISSUE THREAD

**Issue by grotendr** [DCourtel/Wsus_Package_Publisher#76]
Could you tell us a bit more about how this integrates (technically) with WSUS. We want to use it for JRE deployment but senior technical staff is worried about what this does to the WSUS Database. Also do you know if Microsoft still supports WSUS if this is used?

Best regards,
Robin Grotendorst

**Comment by DCourtel** [comment]
Hi, WPP relies on the MS WSUS [SDK](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/bb902470(v=vs.85)?redirectedfrom=MSDN) to publish third-party updates. It doesn’t make any change in the database unless you set it to have third-party updates visible in the WSUS console (Tools -> Settings -> Servers tab). In this case, it changes the "IsLocallyPublished" field of the "[SUSDB].[dbo].[tbUpdate]" table.
Concerning MS support, only Microsoft can answer this question. I guess they will as WPP uses their SDK.

**Comment by grotendr** [comment]
Thanks for the quick answer!
