### ISSUE TITLE
WPP sync issue Replica WSUS

### ISSUE THREAD

**Issue by NauGui** [DCourtel/Wsus_Package_Publisher#77]
Hi,

I'm meeting an issue on my replica server the WPP package not synch on the replica. No folder create on WsusContent the path is red on the WPP. The certificate is the same from the upstream server. I had another Replica and it's working perfectly.

Do you have any idea ?

Thank,

**Comment by DCourtel** [comment]
Did you check if the certificate used to sign the packages is trusted by the replica server?
