### ISSUE TITLE
WPP Crashes when Creating Package OR Create Superseded Package

### ISSUE THREAD

**Issue by st00785** [DCourtel/Wsus_Package_Publisher#78]
Hi there,
              I've noticed an issue with WPP on a new WS2022 host running WSUS. When I click on Create an Update OR Create a Superseding Package - WPP will crash intermittently (not everytime).

Checking Event Viewer I find the following:
Faulting application name: Wsus Package Publisher.exe, version: 1.4.2204.9, time stamp: 0x625152ef
Faulting module name: CylanceMemDef64.dll, version: 2.43.0.469, time stamp: 0x61006a52
Exception code: 0xc00000fd
Fault offset: 0x0000000000010766
Faulting process id: 0x1910
Faulting application start time: 0x01d8b5d1f63f7b8c
Faulting application path: D:\WPP\Wsus Package Publisher.exe
Faulting module path: C:\Program Files\Cylance\Desktop\CylanceMemDef64.dll
Report Id: 1b98d4f9-4d25-4aac-b5f6-f6dd0949c5b3
Faulting package full name: 
Faulting package-relative application ID: 

I can confirm Cylance AV is installed on this Server which I believe might have something to do with the crashing. Interestingly I had this running fine on WS2019 with no issues at all and did not see any such crash issues.

So I am trying to ascertain if this is a WPP issue OR is it a Cylance issue? I can confirm that when Cylance is disabled that WPP appears to work fine so me thinks more of a Cylance issue. Just wondering if there is a list of AV exclusions or whitelistings that WPP may need?

**Comment by DCourtel** [comment]
Can you take a look at this article: [Cylance 1580 has been deployed and the world is on fire](https://www.reddit.com/r/Cylance/comments/p7gf1w/cylance_1580_has_been_deployed_and_the_world_is/)

**Comment by st00785** [comment]
Ah yep - I reckon that might be it. We've logged a ticket with Blackberry to resolve this issue but for now we have our detection methods turned right down on our WPP Server until Blackberry are able to provide a permanent solution.
Thanks heaps for the article! :)
