### ISSUE TITLE
WPP crash on importing Reader or Flash Updates

### ISSUE THREAD

**Issue by StadtBadWurzach** [DCourtel/Wsus_Package_Publisher#8]
Hi,
with the Version 1.4.1904.29  of WPP we get an error, if we try to Import a update for Adobe Reader or Adobe Flash Player.

Error:
![2019-06-18 08_30_28-Remote Desktop Manager  wsus02](https://user-images.githubusercontent.com/43094829/59658252-5e577f00-91a3-11e9-9ffc-6a8207cf650e.png)

Settings:
![2019-06-18 08_27_49-Remote Desktop Manager  wsus02](https://user-images.githubusercontent.com/43094829/59658132-16d0f300-91a3-11e9-9c08-198df010efbc.png)

Version, which i try to import:
![2019-06-18 08_29_41-Remote Desktop Manager  wsus02](https://user-images.githubusercontent.com/43094829/59658226-51d32680-91a3-11e9-909e-ee412a2a4425.png)

Please tell me an email address for the logfile wpp.log.

**Comment by DCourtel** [comment]
Please use Release v1.4.1906.3 instead.

**Comment by StadtBadWurzach** [comment]
Sorry, i write the wrong Version. We use 1.4.1906.3.

**Comment by ati0840021s** [comment]
J'ai l'impression que le problème vient des catalogues Adobe.
Impossible d'importer des mises à jour valide. J'ai les release v1.3.1702.27 et v1.3.1702.10

I get the impression that the problem comes from Adobe catalogs.
Can not import valid updates. I have the release v1.3.1702.27 and v1.3.1702.10

**Comment by ati0840021s** [comment]
De mon coté problème avec serveur wsus depuis mises à jour Windows 2019-06. Version du serveur 2008 R2 standard
On my side problem with wsus server since Windows updates 2019-06. Standard 2008 R2 server version

**Comment by DCourtel** [comment]
What catalog are you using? URL and filename.
![WPPCatalog](https://user-images.githubusercontent.com/13787283/60736456-4f205180-9f57-11e9-9aef-68ae74bf4170.png)

**Comment by StadtBadWurzach** [comment]
Here our current configuration.
![2019-07-06 10_45_42-Remote Desktop Manager  wsus02](https://user-images.githubusercontent.com/43094829/60754021-791b5780-9fdb-11e9-9c97-6d9f89e67b09.png)

**Comment by DCourtel** [comment]
I didn't have any issues to publish those updates. Can you give it a try once again? Maybe, it was a problem with the catalog file.

**Comment by StadtBadWurzach** [comment]
I try it again today. The error is still the same as in the first picture in the issue.

**Comment by StadtBadWurzach** [comment]
After some tests i know some more. The error happens, if i try to add a update where the vendor Name is "Adobe". It looks like as anywhere in WPP or the database the Name already exist. Does somebody know where i have to search for it?

Alternatively I would have to know which SQL commands are executed. So i can reproduce the fault with the microsoft sql management studio - step by step.
