### ISSUE TITLE
Custom Update files tagged as malware by CarbonBlack

### ISSUE THREAD

**Issue by rfrafi** [DCourtel/Wsus_Package_Publisher#80]
![image](https://user-images.githubusercontent.com/3208482/204166044-874c0008-ed68-4bd7-b18e-4835d19dc748.png)

**Comment by rfrafi** [comment]
I think this could be fixed by code-signing.

**Comment by DCourtel** [comment]
That would require an Enterprise certificate issued by a public trusted CA.

**Comment by gruppenrichtlinien** [comment]
You can use easily a SelfSigned Certificate. In the end, you need to trust the End-Entity, not the root.

**Comment by rfrafi** [comment]
Understood. I checked the executables hashes against virustotal just for
the sake of due diligence, and was able to create an exception to allow the
blocked WPP programs to execute. We can tag this one as resolved.

Thank you for being on top of things and for your wonderful creation.

All the best,

RFR
