### ISSUE TITLE
Failed to sign package

### ISSUE THREAD

**Issue by BilliBob** [DCourtel/Wsus_Package_Publisher#81]
![image](https://user-images.githubusercontent.com/7032543/212276294-ca5a8189-1004-4db7-9a91-38966c82f6c9.png)

**Comment by DCourtel** [comment]
2147954407 = The server name or address could not be resolved
Please see: [update-publishing-fails-when-proxy-is-in-use-and-timestamping-is-enabled](https://patchmypc.com/update-publishing-fails-when-proxy-is-in-use-and-timestamping-is-enabled)
