### ISSUE TITLE
Failed to sign package; error was: 2149122451 certificate is generated. Proxy do not use,server is connected to the internet

### ISSUE THREAD

**Issue by shestakow1993** [DCourtel/Wsus_Package_Publisher#82]
`17.01.2023 12:47:26	=================================================================================================================
17.01.2023 12:47:26	Starting. Release : 1.4.2204.9
17.01.2023 12:47:26	Upgrade Settings : True
17.01.2023 12:47:26	Windows was installed in : ru (Russian)
17.01.2023 12:47:26	Entering Void .ctor() : FrmSettings
17.01.2023 12:47:26	Language is : Anglais.
17.01.2023 12:47:26	Entering Wsus_Package_Publisher.WsusWrapper GetInstance()
17.01.2023 12:47:26	Entering Void .ctor() : UpdateControl
17.01.2023 12:47:26	Entering Void .ctor() : UpdateListViewer
17.01.2023 12:47:26	Entering Wsus_Package_Publisher.WsusWrapper GetInstance()
17.01.2023 12:47:26	Entering Void .ctor() : UpdateDetailViewer
17.01.2023 12:47:26	Entering Wsus_Package_Publisher.Credentials GetInstance()
17.01.2023 12:47:26	CredentialNotice set to : Features connecting to remote computers will ask you for credentials.
17.01.2023 12:47:26	CredentialNotice set to : Features connecting to remote computers will ask you for credentials.
17.01.2023 12:47:26	Entering Wsus_Package_Publisher.WsusWrapper GetInstance()
17.01.2023 12:47:26	Entering Void chkCmbBxFilter_SelectionChanged()
17.01.2023 12:47:26	Entering Void DisplayUpdates(Microsoft.UpdateServices.Administration.UpdateCollection)
17.01.2023 12:47:26	Entering Void ClearDisplay()
17.01.2023 12:47:26	Entering Void ClearBeforeConnecting()
17.01.2023 12:47:26	Entering Void ClearDisplay()
17.01.2023 12:47:26	Entering Void ResetControl()
17.01.2023 12:47:26	Entering Void ClearDisplay()
17.01.2023 12:47:26	Entering Void AdjustSplitterDistance()
17.01.2023 12:47:26	Entering Void .ctor() : ComputerControl
17.01.2023 12:47:26	Entering Void .ctor() : ComputerListViewer
17.01.2023 12:47:26	Entering Wsus_Package_Publisher.Credentials GetInstance()
17.01.2023 12:47:26	Entering Wsus_Package_Publisher.WsusWrapper GetInstance()
17.01.2023 12:47:26	Entering Wsus_Package_Publisher.Credentials GetInstance()
17.01.2023 12:47:26	Entering Void .ctor() : ComputerDetailViewer
17.01.2023 12:47:26	Entering Void dtpInstalledAfter_ValueChanged(System.Object, System.EventArgs)
17.01.2023 12:47:26	Entering Void Display(System.Windows.Forms.DataGridViewSelectedRowCollection)
17.01.2023 12:47:26	Entering Void dtpInstalledAfter_ValueChanged(System.Object, System.EventArgs)
17.01.2023 12:47:26	Entering Void Display(System.Windows.Forms.DataGridViewSelectedRowCollection)
17.01.2023 12:47:26	Entering Wsus_Package_Publisher.WsusWrapper GetInstance()
17.01.2023 12:47:26	Entering Void FrmWsusPackagePublisher_Shown(System.Object, System.EventArgs)
17.01.2023 12:47:26	Entering Void FillServerList()
17.01.2023 12:47:26	Entering System.Collections.Generic.List`1[Wsus_Package_Publisher.WsusServer] LoadServerSettings()
17.01.2023 12:47:26	Entering System.Collections.Generic.List`1[Wsus_Package_Publisher.WsusServer] LoadServerSettings()
17.01.2023 12:47:26	Entering System.Collections.Generic.List`1[Wsus_Package_Publisher.WsusServer] LoadServerSettings() : BTC-VSRV-NWSUS
17.01.2023 12:47:26	Name : BTC-VSRV-NWSUS
17.01.2023 12:47:26	Entering System.Collections.Generic.List`1[Wsus_Package_Publisher.WsusServer] LoadServerSettings() : True
17.01.2023 12:47:26	IsLocal : True
17.01.2023 12:47:26	Entering Void set_Port(Int32) : 443
17.01.2023 12:47:26	Port : 443
17.01.2023 12:47:26	Entering System.Collections.Generic.List`1[Wsus_Package_Publisher.WsusServer] LoadServerSettings() : False
17.01.2023 12:47:26	UseSSL : False
17.01.2023 12:47:26	Entering System.Collections.Generic.List`1[Wsus_Package_Publisher.WsusServer] LoadServerSettings() : True
17.01.2023 12:47:26	ignoreCertErrors : True
17.01.2023 12:47:26	Entering System.Collections.Generic.List`1[Wsus_Package_Publisher.WsusServer] LoadServerSettings() : 0
17.01.2023 12:47:26	Entering System.Collections.Generic.List`1[Wsus_Package_Publisher.WsusServer] LoadServerSettings() : 0
17.01.2023 12:47:26	Entering System.Collections.Generic.List`1[Wsus_Package_Publisher.WsusServer] LoadServerSettings() : 0
17.01.2023 12:47:26	Entering Void set_VisibleInWsusConsole(MakeVisibleInWsusPolicy) : Never
17.01.2023 12:47:26	Adding server : BTC-VSRV-NWSUS
17.01.2023 12:47:26	Returning 1 Servers.
17.01.2023 12:47:26	Entering Void .ctor(System.String, Boolean, Int32, Boolean, Int32, Int32, Int32) : BTC-VSRV-NWSUS, True, 443, False, 0, 0, 0
17.01.2023 12:47:26	Entering Void set_Name(System.String) : BTC-VSRV-NWSUS
17.01.2023 12:47:26	Entering Void .ctor(System.String, Boolean, Int32, Boolean, Int32, Int32, Int32) : True
17.01.2023 12:47:26	Entering Void set_Port(Int32) : 443
17.01.2023 12:47:26	Entering Void .ctor(System.String, Boolean, Int32, Boolean, Int32, Int32, Int32) : False
17.01.2023 12:47:26	Entering Void set_DeadLineDaysSpan(Int32) : 0
17.01.2023 12:47:26	Entering Void set_DeadLineHour(Int32) : 0
17.01.2023 12:47:26	Entering Void set_DeadLineMinute(Int32) : 0
17.01.2023 12:47:26	Entering Void set_VisibleInWsusConsole(MakeVisibleInWsusPolicy) : Never
17.01.2023 12:47:26	Entering System.Object Clone() : True
17.01.2023 12:47:26	Wsus Server BTC-VSRV-NWSUS added to the Combobox
17.01.2023 12:47:26	WPP is up and ready
17.01.2023 12:47:26	Will try to connect to the last used server : btc-vsrv-nwsus
17.01.2023 12:47:26	Entering Void ConnectToServer(System.Object, System.EventArgs)
17.01.2023 12:47:26	Entering Void ClearBeforeConnecting()
17.01.2023 12:47:26	Entering Void ClearDisplay()
17.01.2023 12:47:26	Entering Void ResetControl()
17.01.2023 12:47:26	Entering Void ClearDisplay()
17.01.2023 12:47:26	Entering Void AdjustSplitterDistance()
17.01.2023 12:47:26	Entering Void .ctor() : ComputerControl
17.01.2023 12:47:26	Entering Void .ctor() : ComputerListViewer
17.01.2023 12:47:26	Entering Wsus_Package_Publisher.Credentials GetInstance()
17.01.2023 12:47:26	Entering Wsus_Package_Publisher.WsusWrapper GetInstance()
17.01.2023 12:47:26	Entering Wsus_Package_Publisher.Credentials GetInstance()
17.01.2023 12:47:26	Entering Void .ctor() : ComputerDetailViewer
17.01.2023 12:47:26	Entering Void dtpInstalledAfter_ValueChanged(System.Object, System.EventArgs)
17.01.2023 12:47:26	Entering Void Display(System.Windows.Forms.DataGridViewSelectedRowCollection)
17.01.2023 12:47:26	Entering Void dtpInstalledAfter_ValueChanged(System.Object, System.EventArgs)
17.01.2023 12:47:26	Entering Void Display(System.Windows.Forms.DataGridViewSelectedRowCollection)
17.01.2023 12:47:26	Entering Wsus_Package_Publisher.WsusWrapper GetInstance()
17.01.2023 12:47:26	Try connecting to : BTC-VSRV-NWSUS
17.01.2023 12:47:26	Entering Void StartWaitingForm(System.String)
17.01.2023 12:47:27	Entering Boolean Connect(Wsus_Package_Publisher.WsusServer, System.String) : BTC-VSRV-NWSUS (Local), en
17.01.2023 12:47:28	Connected to local Wsus
17.01.2023 12:47:28	Entering System.Version GetConsoleVersion()
17.01.2023 12:47:28	Entering Void set_UserRole(Microsoft.UpdateServices.Administration.UpdateServerUserRole) : Administrator
17.01.2023 12:47:28	Entering CertificateStatus CheckCertificateStatus(Microsoft.UpdateServices.Administration.IUpdateServerConfiguration)
17.01.2023 12:47:28	Entering System.String GetTempFolder()
17.01.2023 12:47:28	Will return : C:\Users\adminaduser\AppData\Local\Temp\WPP\dyfdw4zs.slg\
17.01.2023 12:47:28	Trying to get certificate from server.
17.01.2023 12:47:28	Successfuly got certificate from server.
17.01.2023 12:47:28	EffectiveDate : 17.01.2023 7:00:45 / ExpirationDate : 17.01.2028 7:00:45
17.01.2023 12:47:28	Valid
17.01.2023 12:47:28	Entering Void set_GetCertificateStatus(CertificateStatus) : Valid
17.01.2023 12:47:28	Entering Int32 CheckCertificateKeyLength(Microsoft.UpdateServices.Administration.IUpdateServerConfiguration)
17.01.2023 12:47:28	Entering System.String GetTempFolder()
17.01.2023 12:47:28	Will return : C:\Users\adminaduser\AppData\Local\Temp\WPP\kn2gjeyf.bhj\
17.01.2023 12:47:28	Entering Int32 GetCertificateKeyLength(System.String) : C:\Users\adminaduser\AppData\Local\Temp\WPP\kn2gjeyf.bhj\certificate.cer
17.01.2023 12:47:28	Will return 2048
17.01.2023 12:47:28	Will return : 2048
17.01.2023 12:47:28	Entering Boolean Connect(Wsus_Package_Publisher.WsusServer, System.String) : 2048
17.01.2023 12:47:28	Successfuly connected to Wsus server.
17.01.2023 12:47:28	This is not a Replica server.
17.01.2023 12:47:28	Entering PopulateTreeviewWithComputerGroups. With group : All Computers And node : All Computers
17.01.2023 12:47:28	Entering PopulateTreeviewWithComputerGroups. With group : GO And node : GO
17.01.2023 12:47:28	Entering PopulateTreeviewWithComputerGroups. With group : Unassigned Computers And node : Unassigned Computers
17.01.2023 12:47:28	Entering PopulateComputerGroups. With node : All Computers And computersGroup : All Computers
17.01.2023 12:47:28	Entering PopulateComputerGroups. With node : GO And computersGroup : GO
17.01.2023 12:47:28	Entering PopulateComputerGroups. With node : Unassigned Computers And computersGroup : Unassigned Computers
17.01.2023 12:47:28	Entering Void FillMetaGroups()
17.01.2023 12:47:28	Entering InitializeMetaGroups. With wsusServer : BTC-VSRV-NWSUS
17.01.2023 12:47:28	Entering InitializeComputerGroups With WsusServer : BTC-VSRV-NWSUS
17.01.2023 12:47:28	Entering Void PopulateMetaGroupNode()
17.01.2023 12:47:28	Entering Void CollectUpdates()
17.01.2023 12:47:28	Entering Void CreateNewCompany(Microsoft.UpdateServices.Administration.IUpdateCategory, Boolean)
17.01.2023 12:47:28	Adding : Local Publisher With ID : 7c40e8c2-01ae-47f5-9af2-6e75a0582518
17.01.2023 12:47:28	Entering GetProductNode. For Company : Local Publisher and Category : Locally published packages
17.01.2023 12:47:28	Entering Void .ctor(System.Guid, System.String, Wsus_Package_Publisher.Company) : 5cc25303-143f-40f3-a2ff-803a1db69955, Locally published packages From Local Publisher
17.01.2023 12:47:28	Entering Void set_ProductName(System.String) : Locally published packages
17.01.2023 12:47:28	Entering Void .ctor(System.Guid, System.String, Wsus_Package_Publisher.Company) : Local Publisher
17.01.2023 12:47:28	Entering Void SetComputerGroups(Wsus_Package_Publisher.ComputerGroup, System.Windows.Forms.TreeNode)
17.01.2023 12:47:28	Entering Void SetComputerGroups(Wsus_Package_Publisher.ComputerGroup, System.Windows.Forms.TreeNode)
17.01.2023 12:47:28	Entering Void FillComputerGroup(Wsus_Package_Publisher.ComputerGroup) : All Computers
17.01.2023 12:47:28	Entering Void FillComputerGroup(Wsus_Package_Publisher.ComputerGroup) : GO
17.01.2023 12:47:28	Entering Void FillComputerGroup(Wsus_Package_Publisher.ComputerGroup) : Unassigned Computers
17.01.2023 12:47:28	Entering Void StopWaitingForm()
17.01.2023 12:47:28	Entering Void CheckSubscriptions()
17.01.2023 12:47:28	Entering Void TrvWsus_AfterSelect(System.Object, System.Windows.Forms.TreeViewEventArgs)
17.01.2023 12:47:28	Server
17.01.2023 12:47:28	Entering Void InitializeContextMenuForServer()
17.01.2023 12:47:28	Server Version is : 10.0.17763.2931
17.01.2023 12:47:28	Console Version is : 10.0.17763.2931
17.01.2023 12:47:28	Local OS is : Microsoft Windows NT 6.2.9200.0
17.01.2023 12:47:28	Reporting stat…
17.01.2023 12:47:29	Reporting done
17.01.2023 12:47:40	Entering Void TrvWsus_NodeMouseClick(System.Object, System.Windows.Forms.TreeNodeMouseClickEventArgs)
17.01.2023 12:47:40	Entering Void TrvWsus_AfterSelect(System.Object, System.Windows.Forms.TreeViewEventArgs)
17.01.2023 12:47:40	Company or Updates
17.01.2023 12:47:40	Entering Void InitializeContextMenuForCompany()
17.01.2023 12:47:43	Entering Void CreateUpdatetoolStripMenuItem_Click(System.Object, System.EventArgs)
17.01.2023 12:47:43	Entering CreateNewUpdate with xmlAction : 
17.01.2023 12:47:43	Entering Void .ctor() : FrmUpdateRulesWizard
17.01.2023 12:47:44	Entering Void grpDsp1_SelectionChange(Wsus_Package_Publisher.GroupDisplayer)
17.01.2023 12:47:44	Entering Void grpDsp1_SelectionChange(Wsus_Package_Publisher.GroupDisplayer)
17.01.2023 12:47:44	Entering Void grpDsp1_SelectionChange(Wsus_Package_Publisher.GroupDisplayer)
17.01.2023 12:47:44	Entering Void grpDsp1_SelectionChange(Wsus_Package_Publisher.GroupDisplayer)
17.01.2023 12:47:44	Entering Void .ctor() : FrmUpdateFilesWizard
17.01.2023 12:47:44	Entering Void .ctor() : FrmUpdateRulesWizard
17.01.2023 12:47:44	Entering Void grpDsp1_SelectionChange(Wsus_Package_Publisher.GroupDisplayer)
17.01.2023 12:47:44	Entering Void grpDsp1_SelectionChange(Wsus_Package_Publisher.GroupDisplayer)
17.01.2023 12:47:44	Entering Void grpDsp1_SelectionChange(Wsus_Package_Publisher.GroupDisplayer)
17.01.2023 12:47:44	Entering Void grpDsp1_SelectionChange(Wsus_Package_Publisher.GroupDisplayer)
17.01.2023 12:47:44	Entering Void .ctor(System.Collections.Generic.Dictionary`2[System.Guid,Wsus_Package_Publisher.Company]) : FrmUpdateWizard
17.01.2023 12:47:44	Entering Void InitializeComponent(System.Collections.Generic.Dictionary`2[System.Guid,Wsus_Package_Publisher.Company], Wsus_Package_Publisher.Company, Wsus_Package_Publisher.Product, Microsoft.UpdateServices.Administration.SoftwareDistributionPackage)
17.01.2023 12:47:44	Entering Wsus_Package_Publisher.WsusWrapper GetInstance()
17.01.2023 12:47:44	Entering Void .ctor(System.Collections.Generic.Dictionary`2[System.Guid,Wsus_Package_Publisher.Company], Wsus_Package_Publisher.Company, Wsus_Package_Publisher.Product, Microsoft.UpdateServices.Administration.SoftwareDistributionPackage) : FrmUpdateInformationsWizard
17.01.2023 12:47:44	Entering Void FillPrerequisites()
17.01.2023 12:47:44	Entering Void InitializeComponent(Wsus_Package_Publisher.Company, Wsus_Package_Publisher.Product, Microsoft.UpdateServices.Administration.SoftwareDistributionPackage)
17.01.2023 12:47:44	Entering Void InitializeUpdateFilesWizard()
17.01.2023 12:47:44	Entering Void FrmUpdateWizard_Shown(System.Object, System.EventArgs)
17.01.2023 12:47:44	CurrentDirectory is : C:\Users\adminaduser\Desktop\Release.v1.4.2203.19
17.01.2023 12:48:54	Entering Void btnBrowseUpdateFile_Click(System.Object, System.EventArgs)
17.01.2023 12:48:56	Entering Void txtBxUpdateFile_TextChanged(System.Object, System.EventArgs)
17.01.2023 12:48:56	Setting UpdateFileName : C:\Users\adminaduser\Desktop\7z2201-x64.exe
17.01.2023 12:48:56	Entering Void SetFileType(System.String) : .exe
17.01.2023 12:48:56	Setting File Type : Executable
17.01.2023 12:48:56	Update File : C:\Users\adminaduser\Desktop\7z2201-x64.exe
17.01.2023 12:48:57	Entering Void updateFilesWizard_btnNext_Click(System.Object, System.EventArgs)
17.01.2023 12:48:57	Entering Void InitializeUpdateLevelwithXml(System.String)
17.01.2023 12:48:57	Entering Void grpDsp1_SelectionChange(Wsus_Package_Publisher.GroupDisplayer)
17.01.2023 12:48:57	Entering Void grpDsp1_SelectionChange(Wsus_Package_Publisher.GroupDisplayer)
17.01.2023 12:48:57	Entering Void InitializeUpdateLevelwithXml(System.String)
17.01.2023 12:48:57	Entering Void grpDsp1_SelectionChange(Wsus_Package_Publisher.GroupDisplayer)
17.01.2023 12:48:57	Entering Void grpDsp1_SelectionChange(Wsus_Package_Publisher.GroupDisplayer)
17.01.2023 12:48:57	Entering Void InitializeInformationsWizard() : False
17.01.2023 12:49:04	Entering Void cmbBxVendorName_TextChanged(System.Object, System.EventArgs)
17.01.2023 12:49:04	cmbBxVendorName has index -1 Selected.
17.01.2023 12:49:04	Entering Void cmbBxVendorName_TextChanged(System.Object, System.EventArgs) : 7
17.01.2023 12:49:04	Entering Void cmbBxVendorName_TextChanged(System.Object, System.EventArgs)
17.01.2023 12:49:04	cmbBxVendorName has index -1 Selected.
17.01.2023 12:49:04	Entering Void cmbBxVendorName_TextChanged(System.Object, System.EventArgs) : 7z
17.01.2023 12:49:04	Entering Void cmbBxVendorName_TextChanged(System.Object, System.EventArgs)
17.01.2023 12:49:04	cmbBxVendorName has index -1 Selected.
17.01.2023 12:49:04	Entering Void cmbBxVendorName_TextChanged(System.Object, System.EventArgs) : 7zi
17.01.2023 12:49:05	Entering Void cmbBxVendorName_TextChanged(System.Object, System.EventArgs)
17.01.2023 12:49:05	cmbBxVendorName has index -1 Selected.
17.01.2023 12:49:05	Entering Void cmbBxVendorName_TextChanged(System.Object, System.EventArgs) : 7zio
17.01.2023 12:49:46	Entering Void updateInformationsWizard_btnPrevious_Click(System.Object, System.EventArgs)
17.01.2023 12:49:46	Entering Void InitializeUpdateFilesWizard()
17.01.2023 12:49:47	Entering Void btnBrowseUpdateFile_Click(System.Object, System.EventArgs)
17.01.2023 12:49:50	Entering Void txtBxUpdateFile_TextChanged(System.Object, System.EventArgs)
17.01.2023 12:49:50	Setting UpdateFileName : C:\Users\adminaduser\Desktop\7z2201-x64.msi
17.01.2023 12:49:50	Entering Void SetFileType(System.String) : .msi
17.01.2023 12:49:50	Setting File Type : WindowsInstaller
17.01.2023 12:49:50	Update File : C:\Users\adminaduser\Desktop\7z2201-x64.msi
17.01.2023 12:49:51	Entering Void updateFilesWizard_btnNext_Click(System.Object, System.EventArgs)
17.01.2023 12:49:51	Msi Code : {23170F69-40C1-2702-2201-000001000000}
17.01.2023 12:49:51	Msi Vendor : Igor Pavlov
17.01.2023 12:49:51	MSi Product : 7-Zip 22.01 (x64 edition)
17.01.2023 12:49:51	Entering Void InitializeUpdateLevelwithXml(System.String)
17.01.2023 12:49:51	Entering Void grpDsp1_SelectionChange(Wsus_Package_Publisher.GroupDisplayer)
17.01.2023 12:49:51	Entering Void grpDsp1_SelectionChange(Wsus_Package_Publisher.GroupDisplayer)
17.01.2023 12:49:51	Entering Void InitializeUpdateLevelwithXml(System.String)
17.01.2023 12:49:51	Entering Void grpDsp1_SelectionChange(Wsus_Package_Publisher.GroupDisplayer)
17.01.2023 12:49:51	Entering Void grpDsp1_SelectionChange(Wsus_Package_Publisher.GroupDisplayer)
17.01.2023 12:49:51	XML at PackageLevel : <msiar:MsiApplicationInstalled />
17.01.2023 12:49:51	Entering Wsus_Package_Publisher.RulesGroup ParseXml(Wsus_Package_Publisher.RulesGroup, System.String, Boolean) : <msiar:MsiApplicationInstalled />
17.01.2023 12:49:51	Entering Wsus_Package_Publisher.GenericRule GetSelectedForm(System.Object) : Msi Application Installed
17.01.2023 12:49:51	Rule Type : Wsus_Package_Publisher.RuleMsiApplicationInstalled
17.01.2023 12:49:51	Entering System.Collections.Generic.Dictionary`2[System.String,System.String] GetAttributes(System.Xml.XmlTextReader)
17.01.2023 12:49:51	Entering Void grpDsp1_SelectionChange(Wsus_Package_Publisher.GroupDisplayer)
17.01.2023 12:49:51	Entering Void grpDsp1_SelectionChange(Wsus_Package_Publisher.GroupDisplayer)
17.01.2023 12:49:51	XML at PackageLevel : <msiar:MsiApplicationInstallable />
17.01.2023 12:49:51	Entering Wsus_Package_Publisher.RulesGroup ParseXml(Wsus_Package_Publisher.RulesGroup, System.String, Boolean) : <msiar:MsiApplicationInstallable />
17.01.2023 12:49:51	Entering Wsus_Package_Publisher.GenericRule GetSelectedForm(System.Object) : Msi Application Installable
17.01.2023 12:49:51	Rule Type : Wsus_Package_Publisher.RuleMsiApplicationInstallable
17.01.2023 12:49:51	Entering System.Collections.Generic.Dictionary`2[System.String,System.String] GetAttributes(System.Xml.XmlTextReader)
17.01.2023 12:49:51	Entering Void grpDsp1_SelectionChange(Wsus_Package_Publisher.GroupDisplayer)
17.01.2023 12:49:51	Entering Void grpDsp1_SelectionChange(Wsus_Package_Publisher.GroupDisplayer)
17.01.2023 12:49:51	Entering Void InitializeVendorName(System.String) : Igor Pavlov
17.01.2023 12:49:51	Not found : Igor Pavlov
17.01.2023 12:49:51	Entering Void cmbBxVendorName_TextChanged(System.Object, System.EventArgs)
17.01.2023 12:49:51	cmbBxVendorName has index -1 Selected.
17.01.2023 12:49:51	Entering Void cmbBxVendorName_TextChanged(System.Object, System.EventArgs) : Igor Pavlov
17.01.2023 12:49:51	Entering Void set_Title(System.String) : 7-Zip 22.01 (x64 edition)
17.01.2023 12:49:51	Entering Void RemoveTransformsCommand()
17.01.2023 12:49:51	Entering Void InitializeInformationsWizard() : False
17.01.2023 12:49:54	cmbBxProductName has index -1 Selected.
17.01.2023 12:49:54	Entering Void cmbBxProductName_TextChanged(System.Object, System.EventArgs) : 7
17.01.2023 12:49:54	Entering Void EnableSupersedesControl()
17.01.2023 12:49:54	cmbBxProductName has index -1 Selected.
17.01.2023 12:49:54	Entering Void cmbBxProductName_TextChanged(System.Object, System.EventArgs) : 7z
17.01.2023 12:49:54	Entering Void EnableSupersedesControl()
17.01.2023 12:49:57	cmbBxProductName has index -1 Selected.
17.01.2023 12:49:57	Entering Void cmbBxProductName_TextChanged(System.Object, System.EventArgs) : 7z.
17.01.2023 12:49:57	Entering Void EnableSupersedesControl()
17.01.2023 12:49:58	cmbBxProductName has index -1 Selected.
17.01.2023 12:49:58	Entering Void cmbBxProductName_TextChanged(System.Object, System.EventArgs) : 7z.e
17.01.2023 12:49:58	Entering Void EnableSupersedesControl()
17.01.2023 12:49:58	cmbBxProductName has index -1 Selected.
17.01.2023 12:49:58	Entering Void cmbBxProductName_TextChanged(System.Object, System.EventArgs) : 7z.ex
17.01.2023 12:49:58	Entering Void EnableSupersedesControl()
17.01.2023 12:49:58	cmbBxProductName has index -1 Selected.
17.01.2023 12:49:58	Entering Void cmbBxProductName_TextChanged(System.Object, System.EventArgs) : 7z.exe
17.01.2023 12:49:58	Entering Void EnableSupersedesControl()
17.01.2023 12:49:59	Entering Void updateInformationsWizard_btnNext_Click(System.Object, System.EventArgs)
17.01.2023 12:49:59	Entering Void InitializeUpdateIsInstalledRulesWizard()
17.01.2023 12:50:01	Entering Void updateIsInstalledRulesWizard_btnNext_Click(System.Object, System.EventArgs)
17.01.2023 12:50:01	Entering Void InitializeUpdateIsInstallableRulesWizard()
17.01.2023 12:50:02	Entering Void updateIsInstallableRulesWizard_btnNext_Click(System.Object, System.EventArgs)
17.01.2023 12:50:02	Entering Void InitializeUpdateApplicabilityMetadata()
17.01.2023 12:50:02	Entering Wsus_Package_Publisher.WsusWrapper GetInstance()
17.01.2023 12:50:02	Entering System.String GetApplicabilityMetadata(Wsus_Package_Publisher.FrmUpdateFilesWizard)
17.01.2023 12:50:03	Entering Void .ctor(Wsus_Package_Publisher.FrmUpdateFilesWizard, Wsus_Package_Publisher.FrmUpdateInformationsWizard, Wsus_Package_Publisher.FrmUpdateRulesWizard, Wsus_Package_Publisher.FrmUpdateRulesWizard, Wsus_Package_Publisher.FrmUpdateApplicabilityMetadata) : FrmUpdatePublisher
17.01.2023 12:50:03	Entering Wsus_Package_Publisher.WsusWrapper GetInstance()
17.01.2023 12:50:03	Entering Void Publish()
17.01.2023 12:50:03	Entering Void PresetVisibleInWsusConsoleChkBx()
17.01.2023 12:50:03	Wsus Is Local : True
17.01.2023 12:50:03	chkBxVisibleInWsusConsoleis False
17.01.2023 12:50:03	Entering Microsoft.UpdateServices.Administration.IUpdate PublishUpdate(Wsus_Package_Publisher.FrmUpdateFilesWizard, Wsus_Package_Publisher.FrmUpdateInformationsWizard, Wsus_Package_Publisher.FrmUpdateRulesWizard, Wsus_Package_Publisher.FrmUpdateRulesWizard, Wsus_Package_Publisher.FrmUpdateApplicabilityMetadata)
17.01.2023 12:50:03	File Type : WindowsInstaller
17.01.2023 12:50:03	Entering Microsoft.UpdateServices.Administration.SoftwareDistributionPackage InitializeSdp(Microsoft.UpdateServices.Administration.SoftwareDistributionPackage, Wsus_Package_Publisher.FrmUpdateFilesWizard, Wsus_Package_Publisher.FrmUpdateInformationsWizard, Wsus_Package_Publisher.FrmUpdateRulesWizard, Wsus_Package_Publisher.FrmUpdateRulesWizard)
17.01.2023 12:50:03	Entering System.String GetXmlFormattedUpdateLevelRule()
17.01.2023 12:50:03	Entering System.String GetXmlFormattedUpdateLevelRule()
17.01.2023 12:50:03	Entering System.String GetXmlFormattedPackageLevelRule()
17.01.2023 12:50:03	Entering System.String GetXmlFormattedPackageLevelRule()
17.01.2023 12:50:03	Entering Boolean IsValideURL(System.String) : 
17.01.2023 12:50:03	Returning false
17.01.2023 12:50:03	Entering Boolean IsValideURL(System.String) : 
17.01.2023 12:50:03	Returning false
17.01.2023 12:50:03	Entering System.Collections.Generic.List`1[System.Guid] GetSupersedes()
17.01.2023 12:50:03	Entering System.Collections.Generic.List`1[System.Guid] GetPrerequisites()
17.01.2023 12:50:03	Entering System.String GetTempFolder()
17.01.2023 12:50:03	Will return : C:\Users\adminaduser\AppData\Local\Temp\WPP\hhtkclzv.xpd\
17.01.2023 12:50:03	Entering Void CheckMaxFileSize(System.String) : C:\Users\adminaduser\AppData\Local\Temp\WPP\hhtkclzv.xpd\0bfc99f1-db67-4808-b437-535bcba427e3\Bin\
17.01.2023 12:50:03	Entering System.String GetBiggestFile(System.String, Int64) : C:\Users\adminaduser\AppData\Local\Temp\WPP\hhtkclzv.xpd\0bfc99f1-db67-4808-b437-535bcba427e3\Bin\ : -1
17.01.2023 12:50:03	Will return : C:\Users\adminaduser\AppData\Local\Temp\WPP\hhtkclzv.xpd\0bfc99f1-db67-4808-b437-535bcba427e3\Bin\7z2201-x64.msi
17.01.2023 12:50:03	Entering Wsus_Package_Publisher.WsusWrapper GetInstance()
17.01.2023 12:50:03	Current MaxCabFile Size is : 384
17.01.2023 12:50:03	Saving Sdp : <sdp:SoftwareDistributionPackage 
 xmlns="http://www.w3.org/2001/XMLSchema"
 xmlns:bar="http://schemas.microsoft.com/wsus/2005/04/CorporatePublishing/BaseApplicabilityRules.xsd"
 xmlns:bt="http://schemas.microsoft.com/wsus/2005/04/CorporatePublishing/BaseTypes.xsd"
 xmlns:cmd="http://schemas.microsoft.com/wsus/2005/04/CorporatePublishing/Installers/CommandLineInstallation.xsd"
 xmlns:lar="http://schemas.microsoft.com/wsus/2005/04/CorporatePublishing/LogicalApplicabilityRules.xsd"
 xmlns:msi="http://schemas.microsoft.com/wsus/2005/04/CorporatePublishing/Installers/MsiInstallation.xsd"
 xmlns:msiar="http://schemas.microsoft.com/wsus/2005/04/CorporatePublishing/MsiApplicabilityRules.xsd"
 xmlns:msp="http://schemas.microsoft.com/wsus/2005/04/CorporatePublishing/Installers/MspInstallation.xsd"
 xmlns:sdp="http://schemas.microsoft.com/wsus/2005/04/CorporatePublishing/SoftwareDistributionPackage.xsd"
 xmlns:uei="http://schemas.microsoft.com/wsus/2005/04/CorporatePublishing/Installers/UpdateExeInstallation.xsd"
 xmlns:usp="http://schemas.microsoft.com/wsus/2005/04/CorporatePublishing/UpdateServicesPackage.xsd"
 xmlns:drv="http://schemas.microsoft.com/wsus/2005/04/CorporatePublishing/Installers/WindowsDriver.xsd"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  SchemaVersion="1.2"><sdp:Properties PackageID="0bfc99f1-db67-4808-b437-535bcba427e3" CreationDate="2023-01-17T09:50:03.406Z" VendorName="Igor Pavlov" PublicationState="Published" CanSourceBeRequired="false" UpdateType="Software"><sdp:ProductName>7z.exe</sdp:ProductName></sdp:Properties><sdp:LocalizedProperties><sdp:Language>en</sdp:Language><sdp:Title>7-Zip 22.01 (x64 edition)</sdp:Title><sdp:Description>No description available.</sdp:Description></sdp:LocalizedProperties><sdp:ApplicationSpecificData /><sdp:IsInstallable></sdp:IsInstallable><sdp:IsInstalled></sdp:IsInstalled><sdp:InstallableItem ID="c1da8d6a-209d-4446-95b1-0eb0d4a8e773" ><sdp:ApplicabilityRules><sdp:IsInstalled><msiar:MsiApplicationInstalled/></sdp:IsInstalled><sdp:IsSuperseded><msiar:MsiApplicationSuperseded /></sdp:IsSuperseded><sdp:IsInstallable><msiar:MsiApplicationInstallable/></sdp:IsInstallable><sdp:Metadata><msiar:MsiApplicationMetadata><msiar:ProductCode>{23170f69-40c1-2702-2201-000001000000}</msiar:ProductCode></msiar:MsiApplicationMetadata></sdp:Metadata></sdp:ApplicabilityRules><sdp:InstallProperties CanRequestUserInput="false" RequiresNetworkConnectivity="false" Impact="Normal" RebootBehavior="CanRequestReboot" /><sdp:UninstallProperties CanRequestUserInput="false" RequiresNetworkConnectivity="false" Impact="Normal" RebootBehavior="CanRequestReboot" /><msi:MsiInstallerData ProductCode="{23170f69-40c1-2702-2201-000001000000}" MsiFile="7z2201-x64.msi"/></sdp:InstallableItem></sdp:SoftwareDistributionPackage>

17.01.2023 12:50:05	**** System.InvalidOperationException : Failed to sign package; error was: 2149122451
17.01.2023 12:50:12	Entering Void btnOk_Click(System.Object, System.EventArgs)
17.01.2023 12:50:12	Entering Void Close(System.Object, System.EventArgs)
`

**Comment by DCourtel** [comment]
2149122451 = Forbidden (403)
Please see: [update-publishing-fails-when-proxy-is-in-use-and-timestamping-is-enabled](https://patchmypc.com/update-publishing-fails-when-proxy-is-in-use-and-timestamping-is-enabled)
