### ISSUE TITLE
ProductKiller.exe virus ??

### ISSUE THREAD

**Issue by Adaemas** [DCourtel/Wsus_Package_Publisher#83]
Hello,

I am interested in using the WPP solution at work. But I have a question. There is a file called ProductKiller.exe that comes with WPP. Many antivirus programs detect this file as a virus. Is it necessary to have this file to work correctly with WPP?

Thank you in advance for your answer.

Best regards,
J

**Comment by DCourtel** [comment]
Hi Adaemas, the file is not required for WPP to work. if you remove it, you won’t be able to use the feature to delete an empty product in the Treeview.
