### ISSUE TITLE
can't install update via wpp

### ISSUE THREAD

**Issue by chiquitos1** [DCourtel/Wsus_Package_Publisher#84]
hello,

I can't install update via wpp.

On machine i have an error : 
![image](https://user-images.githubusercontent.com/124031781/215698063-8944618b-1bc0-4db9-8b41-bb34848049a2.png)
can someone help me to resolve this problem ?

Thanks

**Comment by DCourtel** [comment]
If I were you I would investigate a certificate verification problem. Third-party updates are digitally signed and Windows check that certificate, may it fails to do so because of a Date/Time/Time zone issue.
