### ISSUE TITLE
Command Powershell to recertify all Package.

### ISSUE THREAD

**Issue by prisme666** [DCourtel/Wsus_Package_Publisher#85]
Hello,
Following a renewal of the certificate which is about to expire, I have to recertify all the packages in Wsus Publisher packager. 
Is there a command in Powershell that allows me to do this without the graphical interface and especially without having to say OK for each package. 
Thank you for your help and for your product that fills all satisfaction.
Sincerely,
Evers André

**Comment by DCourtel** [comment]
Hi prisme666, one could definitely write a Powershell script to re-sign all third-party updates in WSUS. I don’t have such a tool off hand. If those packages have been published by a recent build of WPP, they are timestamped. That means, even when the certificate has expired, it is still trusted by clients.

**Comment by prisme666** [comment]
Hello, DCourtel
Thank you for your prompt reply.
I close the ticket. 
Sincerely,
Prism66

**Comment by DCourtel** [comment]
I will try to change the behavior of the publisher to avoid acknowledging each time when re-signing.

**Comment by prisme666** [comment]
OK thanks a lot ....
