### ISSUE TITLE
Best practise method of migrating to new WSUS Server with WPP in the picture?

### ISSUE THREAD

**Issue by TreeBranches** [DCourtel/Wsus_Package_Publisher#86]
It's time we finally moved our WSUS server from 2012R2 to 2022. We'll be creating a new server for this as opposed to in-place upgrade.

I was going to perhaps migrate the approvals but was also considering just starting from scratch. However, I'm not sure how any of this will affect WPP.

Do I simply just recreate the updates in WPP or do I have to migrate the database? Do I just export these updates and import the CAB files in the new install? Will it break the superseding update tree or is there a way to migrate that as well?

Edit: We have WSUS using the WID Database software, not MS-SQL or another SQL tool.
Edit2: I'm raising this as an 'issue' because I don't see anything about this in the Wiki :)

**Comment by buuf** [comment]
I know this is 7 months old...

I just did an in-place upgrade from 2012R2 -> 2019 -> 2022 with great results... and some weirdness

1. I had to run some wsus post-commands both upgrade. One asked me to find the original folder path all the wsus updates were on then give it time to re-associate the folder and contents to wsus.
2. A first sync brought back ALL previously declined and removed updates from wsus, taking a good 8-10 hours to finish. Once done then I was able to once again approve/decline then delete all old and unnecessary updates.

All throughout this time WPP worked and was accessible via the parent and child (with SSL on both), Nothing was broken within it (an update from WPP installed on my comp during the in-place upgrade process that I added using 2022) and it looks to be just fine.
