### ISSUE TITLE
Where is the .exe file?

### ISSUE THREAD

**Issue by eulkus** [DCourtel/Wsus_Package_Publisher#9]
M. Courtel -

Pardonnez-moi, cette traduction n’est pas bonne, car j’utilise Google Translate.

J'ai téléchargé le fichier .zip pour WSUS Package Publisher mais je ne trouve pas le fichier .exe.

Pouvez-vous offrir des informations?

Cordialement,

Edward Ulkus

**Comment by DCourtel** [comment]
Please download the .7z file and you will find the EXE file in it
![image](https://user-images.githubusercontent.com/13787283/60287038-3689b900-9911-11e9-8748-aac76eb1c6ce.png)

**Comment by eulkus** [comment]
Merci.
