### ISSUE TITLE
Silently new WPP Version 1.5.2401.21 released?

### ISSUE THREAD

**Issue by sonduko** [DCourtel/Wsus_Package_Publisher#93]
Is a new version for WPP silently released?
Today I get surprised by a new message. When starting WPP it shows a a message "Please Upgrade .NET Framework on this machine"
WPP version info shows 1.5.2401.21 installed which is newer than the one here in the repository. Auto Update Feature was enabled.

**Comment by SwissJay** [comment]
I wonder the same. Binaries updating out of the blue without any kind of a digital signature are quite the red flag, especially when seemingly "official" project sites contain no release notes or other traces of that new version. Very odd!

**Comment by DCourtel** [comment]
Hi @sonduko and @SwissJay, sorry for the scare. Yes, there is a new build of WPP. I didn’t have the time to upload the new binary here.

**Comment by nicorac** [comment]
Please update the README with the new version, even if not yet available in releases page.
Having a binary on my server with a "non-official" version number is quite worrying.

Or, at least, reopen and pin this issue, so people (like me) can find it easily and know everything is ok.
(I was going to downgrade to latest available till I had a look into "closed" issues...)

**Comment by davidtrevor23** [comment]
How to configure the auto update? I am still on 1.4.2203.19 and I do not see any button in the software to search for updates.

**Comment by nicorac** [comment]
> Hi [@sonduko](https://github.com/sonduko) and [@SwissJay](https://github.com/SwissJay), sorry for the scare. Yes, there is a new build of WPP. I didn’t have the time to upload the new binary here.

Almost 2 years from that message and, as of today (2025.11.07), still no release available and no new commits as well.

Installing such a critical piece of software without proper documentation or access to the official source code should be strictly avoided ⛔.

**Comment by davidtrevor23** [comment]
Whenever WSUS Package Publisher is closed, it seems to open SelfUpdater.exe (without any parameters). Running on my client, nothing happens however. And checking with Procmon64 I do not see any network calls from that EXE.

Running from the WSUS server directly (Windows Server 2022), the EXE even gives me an error.

<img width="343" height="204" alt="Image" src="https://github.com/user-attachments/assets/ac38110a-227c-49ed-929c-16f8bd1d27fd" />

**Comment by CoRpO** [comment]
Autoupdate won't work. The domain name is expired and free to register :/ That's a threat in case someone registers it and pushes a malicious update

**Comment by nicorac** [comment]
> That's a threat in case someone registers it and pushes a malicious update

This is a huge security hole IMHO.
I normally turn off auto-updates for this kind of software, but it looks like the ones who didn’t suddenly got updated from who-knows-where.
Pretty worrying, honestly.

@DCourtel : almost two years without updates — could you please let us know if the project is still alive?
Missing updated sources, missing updated binaries and, worst, auto-updated binaries from unknown sources are raising concerns.

**Comment by CoRpO** [comment]
Everybody should rename/move/delete SelfUpdater.exe and SelfUpdaterV2.exe to avoid any problems in the future in case Dcourtel doesn't renew the domain name
