### ISSUE TITLE
Failed to create cab error when publishing Dell BIOS updates

### ISSUE THREAD

**Issue by batmonkeyman** [DCourtel/Wsus_Package_Publisher#94]
Getting a "Failed to create cab; error was: 2147942432" error message when attempting to publish specific Dell BIOS update files for deployment.

**Comment by LeFouineur** [comment]
What parameters do you use ? I update my Dell Bios with WPP without problems

**Comment by batmonkeyman** [comment]
It has been a minute since I initially posted my issue.  I think it had something to do with Crowdstrike on the server.  If I uninstalled it, I then could pull in the BIOS exe file without issue.  Once I put it back on it then would give the same error.  Didn't matter if I had switches or not used.  I then started choosing the option to create a "custom update" and that appeared to create successfully.  That was sometime this past summer that I found that part out.
